### ISSUE TITLE
Implement Prism Offset, Mirror, and other modifiers

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#1]
We should implement Prism Offset, Mirror and other modifiers into the Whack A Mole VR project, see for instance the implementation in La Baguette:
https://github.com/med-material/La-baguette

![image](https://user-images.githubusercontent.com/3967945/56957726-5dfa1a80-6b48-11e9-809a-4d1e74950235.png)

**Comment by QuentinDaveau** [comment]
To do: include #14
