### ISSUE TITLE
Therapist UI: Treatment Program Revamp

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#102]
Instead of providing patterns in a dropdown, we can do better.
- We should relabel this as treatment programs.
- We could use the freed space from the modifiers, to now display different treatment programs in a list which is easy to choose from.
- Each treatment program could also have a description of what it is intended for and what it will consist of.

The mockup below is just the preliminary idea and will be iterated upon:
![image](https://user-images.githubusercontent.com/3967945/95717093-bf467880-0c6c-11eb-821d-dd3e67776610.png)

**Comment by hendrikknoche** [comment]
i think that's a great idea. any way we can address both standard tests and training prefabs?

**Comment by larsevald** [comment]
We should also include the possibility of non-symmetrical patterns.

In any case, a possibility of easily configuring new patterns

**Comment by bastianilso** [comment]
We now have support for both internal and external treatment programs. Eventually I also want to add program descriptions to the list. Configuring new patterns is for now a job one can do from a text editor.
