### ISSUE TITLE
detecting misaligned/swapped controllers

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/Whack_A_Mole_VR#130]
To make it easier for the therapist to detect controllers that are on the 'wrong' side of the body mid-line it would be good to maybe colour code the labels (so the therapist does not have to decode the numbers - which are very helpful) 

I propose the following colouring traffic light scheme 
green - all OK (one/two controllers)
orange - one controller is past the midline but still not past the second controller 
red -
1) one controller / the controller is past the midline 
2) two controllers (the  controller is on the opposite of the designated side of the midline further on that side than the second controller)
![image](https://user-images.githubusercontent.com/1982879/100498388-1f807380-3162-11eb-815d-6501b5acd41c.png)

**Comment by QuentinRoman** [comment]
![Coords](https://user-images.githubusercontent.com/48129386/134501173-803b6438-8d8a-4df1-96d5-08f711c7c33f.gif)
![Player](https://user-images.githubusercontent.com/48129386/134501316-3bfdb386-1892-43cd-881d-652efda2f524.gif)

I replicate the behavior you described in the issue. As you can see both controller coordinates are green when they are on their side, if one of them crosses the midline the coords becomes orange and if the controllers are inverted both coords are red.
It also works with one controller, if one controller is OFF and the other cross the midline the coords turns red.

Maybe it needs more tweaking, like a error message if the controller are swapped, or something else ? Let me know.

**Comment by hendrikknoche** [comment]
OK, let's simplify this.
Let's keep the labels black and switch to red  when the controllers are crossed over. 
We should also add a text label that appears stating the "Controllers SWAPPED" in the space right of the informatio "RIGHT: 0.12"

**Comment by bastianilso** [comment]
![image](https://user-images.githubusercontent.com/3967945/134654825-421cc1ce-c468-479b-abbb-c08405458304.png)
^placement of the label could be here
