### ISSUE TITLE
motorspace: alter placement and size

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#131]
Quote from Lars

> Motor space size: I still believe that the default motor space is too small. I can play the entire game with my elbow on the chair rest and move my forearm 30 cm left-right. I think the default should be twice as big (4x the area) and then it can be calibrated smaller for patients with restricted movements. Also, the placement of left and right motor space on either side of the body midline does not encourage patients to cross their midline. At least when playing with one hand, I would like the patients to be encouraged to cross the midline to hit contralateral moles. I do not have any great idea on how to solve these issues, but I think we should schedule some time to discuss this.

**Comment by bastianilso** [comment]
pull request #133 tries to address the issues raised in here - however, note that enlarging the motor space does make them overlap when motorspace for both left and right hand are enabled. But let us as a starting point agree on the correct size and work from there.

**Comment by IrisBrunner** [comment]
Thanks Bastian

overlapping motor spaces are not necessarily a problem I think. Let's try it out.


Iris
________________________________
Fra: Bastian Ilso ***@***.***>
Sendt: 8. april 2021 10:56:19
Til: med-material/Whack_A_Mole_VR
Cc: Subscribed
Emne: Re: [med-material/Whack_A_Mole_VR] motorspace: alter placement and size (#131)


pull request #133<https://github.com/med-material/Whack_A_Mole_VR/pull/133> tries to address the issues raised in here - however, note that enlarging the motor space does make them overlap when motorspace for both left and right hand are enabled. But let us as a starting point agree on the correct size and work from there.
