### ISSUE TITLE
Better feedback when going off the board

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#142]
* ~~perhaps show arrows about how the patients can get back to the board.~~ (fixed in #166)
 *

**Comment by bastianilso** [comment]
the arrows might want to be parented to the camera, so they are visible clearly to the user.
Also we could use a sound.

**Comment by bastianilso** [comment]
This issue is especially relevant, if we for data analysis purposes would rather have a static interaction (to e.g. force controller movement to be in the same space - targeting the same world position etc).

Here is crude first draft mockup of what we can do when people are not inside the motorspace (we can make this smooth/aesthetically pleasing, but this communicates the principle):
![e16a49733bf083edc22e70ba7cf21d8c7a4a67f2](https://user-images.githubusercontent.com/3967945/135619773-cca9be12-4724-400f-b360-ebb21d6a7ef9.gif)

**Comment by bastianilso** [comment]
@QuentinRoman could you share your progress so far here? ☀

**Comment by QuentinRoman** [comment]
I have implemented a system that can place arrows around the Motor space when the controller is out of the Motor space bound, also added a small animation using the PingPong method.

![OOB](https://user-images.githubusercontent.com/48129386/148553549-eac758bc-8a4f-4dfa-a7d9-7755ff09f578.gif)

I can add more arrows and it will adapt their placement around the Motor space.

![image](https://user-images.githubusercontent.com/48129386/148554135-6c18c0dc-381f-4671-98d0-afb1292579bd.png)

The IEnumerator that I'm working on for changing the size of the Motor space also works with the animation, but as you can see below I still have some visual bugs, sometimes the Bubble Display activating, or when I switch between the Left and Right controller the Motor space have the wrong coordinate.

![OOB animation](https://user-images.githubusercontent.com/48129386/148554353-d9ebd5e5-768f-4499-89ce-c41cbe161934.gif)

When the bugs are fixed, as we discuss we can also add a message or indication directly attached to the player camera, so the player will always have some kind of feedback wherever direction he is looking. 🌴

**Comment by bastianilso** [comment]
@QuentinRoman this is a nice starting point. Once you feel it is ready, I think we should start with getting this merged and have some feedback from real usage, before proceeding to attach an indication directly to the camera.

For case 1 where the hands returns to the motorspace, could you implement a small 200ms delay, where the arrows dissapear first, and then the motorspace fades out, before being completely invisible? (rather than dissappearing immediately)

**Comment by QuentinRoman** [comment]
Here the fade out animation I started working on. I still need to find the right speed and duration to make it feel nicer.

![fadeOut2](https://user-images.githubusercontent.com/48129386/149157460-ca85eff4-fb8e-4f6d-a9f1-396604863f72.gif)

Before starting a pull request, I would like to rewrite/refactor some of my code to make it more optimized and clean, also I still have 1 or 2 bugs/behavior to handle, like the arrows when both motor space are activated and maybe a transition when going from the left to the right motor space. 🏷️ 

![OOB3](https://user-images.githubusercontent.com/48129386/149160620-1a8ce31b-8e76-4d77-baa1-d944fc031d2c.gif)
