### ISSUE TITLE
Code overhaul

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/Whack_A_Mole_VR#16]
Currently the game's code is a bit messy. The different classes are tightly coupled together in a way that makes any change/implementation really hard, or leads to even messier code. Reworking most of the classes so they mostly respect the SOLID principles is a first need. Currently even implementing the new UI isn't possible without modifying most of the start handler code.

**Comment by QuentinDaveau** [comment]
A very basic example of how the classes could be organized:

![basic_uml](https://user-images.githubusercontent.com/45624296/66027734-d00dcb80-e4fb-11e9-928b-a11dca4387b2.png)

**Comment by bastianilso** [comment]
@QuentinDaveau thanks for the proposal. From my own brief look at the code I suggest:

- The GameController class seems OK as class to have.
- The WallController class seems OK as class to have (assuming it provides equivalent functionality as your WallManager).

As for your suggestions, I think Mole class sounds good - For now I don't think we need subclasses which implement Mole per se - we only change the physical apperance and auditive appearance of Mole, so we could load this Prefabs from Resources to accomodate that - See Ressource.Load().

I'm also unsure about SpawnManager and DifficultyManager. I think they could both fit well inside your proposed GameManager for now.

Let me know what you think of this.
If you decide to rename classes/files, please do so in a separate commit.
Also, if it is like you say with the Main Menu that it is too difficult to use the new design with the old code, then I suggest that you perform this restructure first, and then rebase your main menu work on top of it. I can show you how to do that on Monday and we can look into preparing a pull request too.

**Comment by QuentinDaveau** [comment]
@bastianilso thanks for the remarks, here are the reasons of my suggestions:

> As for your suggestions, I think Mole class sounds good - For now I don't think we need subclasses which implement Mole per se - we only change the physical apperance and auditive appearance of Mole, so we could load this Prefabs from Resources to accomodate that - See Ressource.Load().

The subclasses are in anticipation of the issue #13, which may need transition animations. Having a mole's abstract class will give a lot of freedom and simplify the creation of new moles. Of course it is far from necessary, but I think it may not be that hard to implement and could prove to be useful in the futur.

> I'm also unsure about SpawnManager and DifficultyManager. I think they could both fit well inside your proposed GameManager for now.

They were added for the same reason as the abstract mole class, for future-proofing (and also, in this case, to try to respect the Single responsibility principle). For example, right now the difficulties are well defined and hardcoded in the code. However we may want to add new types of difficulties in the future, and maybe having them stored elsewhere, having a dedicated class containing and referencing the different difficulties may be quite useful to prevent having to rewrite code in the Game Manager each time. Of course these classes are not immediately necessary and may never be. However they shouldn't cost much to implement and may always be useful for code readability.

**Comment by bastianilso** [comment]
merged with pull request #19 :cake:
