### ISSUE TITLE
UI: Create therapist UI

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/Whack_A_Mole_VR#17]
Since the UI rework #4 it is necessary to create a UI dedicated to the therapist. This UI may be used at two distinct moments:

- Before the game starts to set the game's properties (game duration, test Id, participant Id, difficulty, start game button);
- While the game is running to apply modifiers and get feedback (mirror effect, prism effect, eye patch, dual task mode, stop test, time passed, time left).

Currently a temporary UI is used to set the game's properties:

![Therapist_UI](https://user-images.githubusercontent.com/45624296/66107217-fdbc4880-e5bf-11e9-8373-2c6c19dd0083.png)

**Comment by QuentinDaveau** [comment]
Added options menu:

![image](https://user-images.githubusercontent.com/45624296/66750653-465fe580-ee8d-11e9-9bfa-dd572722a7c4.png)

I will add a "stop test" button, the time spent and time left. Any suggestion concerning the overall design or options to add/modify ?

**Comment by QuentinDaveau** [comment]
Maybe reducing the opacity of the menu (only keeping the timer visible) when it is not hovered by the cursor, so the therapist can have an easier time seeing the participant behavior.

**Comment by QuentinDaveau** [comment]
To do: add a "calibrate wall" button to set its position so it faces the user (maybe also allow the Therapist to modify the wall height and distance).

**Comment by QuentinDaveau** [comment]
To do, add "show hand" button, referencing issue #12

**Comment by QuentinDaveau** [comment]
@bastianilso That's a pretty awesome design !

**Comment by bastianilso** [comment]
Few more behavioral notes:

- By default, the therapist UI is in expanded mode.
- For the Modifiers part, have a look at how the UI is built in [La Baguette](https://github.com/med-material/La-baguette) - mostly we can just make use of the default look/behavior of the built-in Button components.
- The "Participant 8," "Test 1", "2 minutes" parts, are editable, by hovering the mouse over them, as described in issue #6 
- The UI should be optimized for full-screen play - when we export the game from Unity, it will start in Full screen by default. Most screens nowadays are at least 1280x800px, so I dont expect the UI to support smaller sizes, than that.

**Comment by QuentinDaveau** [comment]
Should the therapist be able to pause/unpause the game by clicking on the small icon on the minimized mode ?

![image](https://user-images.githubusercontent.com/45624296/67086774-ce9dfd80-f1a1-11e9-87db-ae9a9a936c24.png)

**Comment by bastianilso** [comment]
@QuentinDaveau interesting point, but for the time being, let's treat the small bar as one big button which expands to the big UI.

**Comment by QuentinDaveau** [comment]
@bastianilso small question. I guess the "speed" parameter relates to the difficulty of the game. Do we allow to set this parameter while the game is running, like the others ? If that's not the case, maybe we should place it with the "participant", "test" and "duration" parameters.

**Comment by QuentinDaveau** [comment]
@bastianilso We're also missing a "main hand" parameter. Is-it on purpose ?

**Comment by QuentinDaveau** [comment]
Another question: Should the participant welcoming panel (#4) be shown every time that the game is stopped or only once at the beginning ?

**Comment by bastianilso** [comment]
@QuentinDaveau 

> small question. I guess the "speed" parameter relates to the difficulty of the game. Do we allow to set this parameter while the game is running, like the others ? If that's not the case, maybe we should place it with the "participant", "test" and "duration" parameters.

Yea, that's the alternative - if the implementation is easier/simpler like that, then feel free to do so.

> We're also missing a "main hand" parameter. Is-it on purpose ?

hmm, what would the "main hand" parameter be used for?

> Another question: Should the participant welcoming panel (#4) be shown every time that the game is stopped or only once at the beginning ?

For now, whenever the game is stopped.

**Comment by QuentinDaveau** [comment]
@bastianilso Thanks for the answer. For the "main hand" I mean if we activate the left controller or the right (if the participant is right of left handed). I guess the user can also simply swich the controllers from one hand to another, but doing the switch through code could have its uses, for example if we want to log it.

**Comment by QuentinDaveau** [comment]
Issue fixd with merge of #22. Closing it.
