### ISSUE TITLE
Logging: Log when controller moves out of motorspace boundaries

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#173]
We currently log motorspace boundaries and controller boundaries, but it would be handy for data analysis if we logged events from within Unity whenever the VR controller moved inside and outside the motorspace boundaries.

**Comment by bastianilso** [comment]
@Xav1204 I would like you to look into this issue if possible. Some hints:

- Whack-A-Mole VR saves logs to the `Documents/` folder, see the `Event.CSV` file and check how the `Event` column looks in there.
- You will need to introduce changes to the `BubbleDisplay.cs` script.
- For how to log the data, please see how this is done in other cases, examples can be found in e.g. `GameManager`. 

Feel free to ask questions about the logging manager system, I'm happy to help. 👍

**Comment by bastianilso** [comment]
Here is an example from how the Event column looks like in a typical playthrough. As you can see we have events for "Pointer Shoot". This issue is about adding events when the controller leaves motorspace and enters motorspace.

![image](https://user-images.githubusercontent.com/3967945/191274528-e8b59632-6521-4d3e-9791-9245da14e96c.png)

**Comment by Xav1204** [comment]
@bastianilso Is it this kind of event that you want?
![image](https://user-images.githubusercontent.com/73820233/192520093-a1cdc49b-6441-4205-a452-e34a99d047b0.png)

**Comment by bastianilso** [comment]
Looks good, just need better labels:

```
Pointer Outside Motorspace
Pointer Inside Motorspace
```

**Comment by Xav1204** [comment]
![image](https://user-images.githubusercontent.com/73820233/192970187-17440900-f817-4c45-a9db-fa783854d150.png)
@bastianilso before that the game begin, we have the countdown timer panel and during this time, we can move the cursor and might be inside or outside the motorspace. Do we need to log these events? Do I need to disable them during the countdown time?

**Comment by bastianilso** [comment]
@Xav1204 no need to discard them, we can easily filter them out during analysis.

**Comment by Xav1204** [comment]
ok thanks

**Comment by Xav1204** [comment]
![Motorspace](https://user-images.githubusercontent.com/73820233/193536263-971f87ab-27cf-4c92-aa98-1b1da28c0d34.gif)
When the blue square appears, you're no longer in the motorspace and when it disappeared, you're come back to the motorspace.

![image](https://user-images.githubusercontent.com/73820233/193536963-2c0ed380-a629-4bd5-843d-f6893030783c.png)
Moreover, during the countdown time, you might be inside or outside the motorspace. The log will be reported in the log event CSV file but as we have the log "Game Started", we need to be careful to the logs after this one.
