### ISSUE TITLE
HmdCalibration: Make instructions more clear and add fade-out

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#199]
Users are initially presented with a message saying they should hold the controller still which is managed by the `HmdCalibration` script. We should improve the initial user impression in the stage:

- The instructions currently tell people to "stay in rest position", but it's not illustrated what that means. We should update the instructions to include an illustration showing how people are supposed to sit.
- When the user press the button to confirm the position, we abruptly turn off the Calibration Panel. It would be better if we instead fade out the panel. This fade-out should be fast, e.g. 300-500ms max.

Below is a screenshot of a first iteration of a design I propose we could use as a starting point. (we may evaluate what drawing style would fit best).
![image](https://user-images.githubusercontent.com/3967945/191445787-fdfdc134-8ae1-47eb-b70f-27a69d584c8c.png)

@Xav1204 the Calibration panel is currently not a prefab, it may make sense for you to export it as a prefab and update it there. 

You can download the illustration shown in the screenshot here:
[person-resting-position.zip](https://github.com/med-material/Whack_A_Mole_VR/files/9614250/person-resting-position.zip)

**Comment by Xav1204** [comment]
@bastianilso I don't find the script where you close the calibration panel. Can you tell me where I can find it please. Thanks in advance.

**Comment by bastianilso** [comment]
@Xav1204 It's called `HmdCalibration.cs`. If you search for the file name you should find it (in the `Assets/ `folder)

**Comment by bastianilso** [comment]
@Xav1204 the closing happens through a Unity Signal. You can see this if you search for the game object which uses the HmdCalibration script.

**Comment by Xav1204** [comment]
it's good, I find it. Thanks

**Comment by hendrikknoche** [comment]
@bastianilso should we include in the Readme some overview/structure that explains where to find the major building blocks (and which they are)?

**Comment by bastianilso** [comment]
implemented in commit bb0bd44747495a4ed685734359c4ea310297ba38
