### ISSUE TITLE
Treatment Patterns bug testing [urgent]

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#206]
We are preparing 18 treatment programs for an upcoming trial. As part of this, it seems that certain treatment programs don't run according to their script.

Onboarding Session 1
- In the session using right hand with distractors, only one distractor is spawned for the second mole

Mirror Therapy
- The left and right motor space are not similar sizes in pre-/posttest (without mirroring) conditions

@Xav1204 Could you test using the VR headset, whether you can replicate the described issues above. 
You can do this by downloading the ZIP file below and put the files inside `C:\Users\user\AppData\LocalLow\Med-Material\Whack_A_Mole_VR\TestPatterns`. 

[treatment_programs_bugs.zip](https://github.com/med-material/Whack_A_Mole_VR/files/9623530/treatment_programs_bugs.zip)

The treatment programs will then appear in the treatment program selector:

![image](https://user-images.githubusercontent.com/3967945/191689074-fa9d639f-2e2f-4317-9ceb-1dbbe1b68487.png)

Here are some guiding questions:

- Can we replicate the issue by regular playtesting (actually playing the game in VR, shooting the moles)?
- Can the issue be replicated simply by letting the game run, showing the moles?

The goal is to understand under what conditions this might happen. Ideally we can capture the bug in a screen recording.

**Comment by bastianilso** [comment]
@Xav1204 Lars has sent me a video of the issue in "Onboarding Session 1".

The issue happens because when the player shoots the mole at X8Y5, immediately after, a distractor appears in X8Y5. The distractor appears so fast that it is also "shot" by the player.

![image](https://user-images.githubusercontent.com/3967945/191712399-7fae70ab-6637-4ad6-bc1c-17cbed58d0f3.png)

I think the short term solution is that we should simply not show a distractor in the same position as the mole. In this case, because the program is an onboarding program, we can change the position.

However, in the long-term, we should need to investigate whether there is a problem with the implemented "cool-down" in Whack-A-Mole. It should not be possible to "shoot 2 moles with one shot" so to speak.

**Comment by Xav1204** [comment]
@bastianilso I don't have this problem about the stuck ghost cursor.

**Comment by bastianilso** [comment]
closing this and opening separate issues for the remaining problems here.
