### ISSUE TITLE
SaveToCSV: Need UI indication while Whack-A-Mole is saving data

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#211]
Saving to CSV is multi-threaded, to ensure that there is no performance impact on Whack-A-Mole, since saving especially our continuous data can take some processing time. However, there is no UI indication that saving is happening and no warning, if  clinicians try to close Whack-A-Mole VR before saving is finished.

We should design some indication to address this and to avoid data loss.

**Comment by bastianilso** [comment]
@Xav1204 could you make this your next priority? this is important for our partner to get fixed.

It's important we make a clean solution for this, so please read carefully:

- First we need a prefab UI dialog shown to the therapist, if the exit button is pressed and we are done saving.
![image](https://user-images.githubusercontent.com/3967945/192969388-728feb8d-4d29-4e7f-9b41-6277d187c4f3.png)

- In order to know whether we are saving, we need a function in the `LoggingManager.cs` which can be used by the Exit Button via the `TherapistUi.cs` to check whether we are still saving. Have a look at the function `SaveCallback()` in LoggingManager - this is where you can know whether the LoggingManager has finished saving or not (could be a boolean). And then we need to postpone the `Application.Quit()` call until after the saving has finished.

- Alternatively, we could use `OnApplicationQuit()` inside `GameDirector.cs` - but I'm not sure to what extend we can use to to "postpone" quitting. Have a look..

**Comment by bastianilso** [comment]
In addition to this, we may want a general text indication in the therapist UI.
I suggest you drive this indication by making LoggingManager emit a `UnityEvent`, and use `text.SetActive()`

![image](https://user-images.githubusercontent.com/3967945/192974463-146ae8f0-7934-4737-8eab-f87823e5e283.png)

**Comment by Xav1204** [comment]
![image](https://user-images.githubusercontent.com/73820233/193515629-d948e1ad-f06d-469c-a21f-db604f5de8a4.png)
@bastianilso At the moment I have put in an indicator to show to the therapist how many files are saved. Should I put in a UI element like a progress bar or something else instead of the text on the left or should I leave it like that?

**Comment by Xav1204** [comment]
![Save1](https://user-images.githubusercontent.com/73820233/193528697-0f56dec2-c95a-4fa3-8141-af7adec0331a.gif)
We can see some updates on the UI elements in particular on the save status on the left bottom and also the number of files which are saved on the right top.

![Save2](https://user-images.githubusercontent.com/73820233/193529235-b9c09b8c-69a4-49ea-b0f6-b309387c4aa6.gif)
When all the files are not saved, we have the warning message panel which open and at the end of the save, the app closes automatically and we can see that all the csv files are downloaded.

**Comment by hendrikknoche** [comment]
it would be good to have a progress bar. but for now maybe this is sufficient. After the saving is done and the green button appears the pink-ish background should disappear shortly after reaching n/n.

**Comment by Xav1204** [comment]
@hendrikknoche thanks for your answer I will do it now.

**Comment by bastianilso** [comment]
resolved with #214 #226 #232
