### ISSUE TITLE
Logging: MoleType column is not always in dataset

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#212]
In commit 57961dbfd1404ab77748757fa2de8576eaa5a328 we introduced logging of `MoleType` in `Mole.cs` logging, so that we knew whether the mole was facing right or left, but it seems like this information doesn't always appear in the dataset.

We need to verify if the issue replicatable and what causes it.

**Comment by Xav1204** [comment]
![image](https://user-images.githubusercontent.com/73820233/194054223-04aa5edc-072d-4fc1-b567-b47cc9b05750.png)

@bastianilso this issue is solved?

**Comment by bastianilso** [comment]
@Xav1204 yes, the point is to have the MoleType column in the logging dataset. Note, that this is not about writing code such that it appears, the point is to investigate why the MoleType column doesn't appear, so we can arrive at some possible technical explanation (bug in LoggerNotifier? Mole.cs code is never called? etc). You can report here what you try and what you find out. 🙂👍

**Comment by bastianilso** [comment]
fixed with commit [610bc1](https://github.com/med-material/Whack_A_Mole_VR/commit/e610bc19812a4ddb504cc0c10d9af199874f9865)
