### ISSUE TITLE
Motorspace indication: indicate on wall instead of motorspace

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#213]
People keep track of the cursor on the wall when playing, rather than their hand. For this reason, weep the signifier arrow graphics on the wall .
So we could e.g. just have an arrow pointing on the wall itself.

A signifier should be on the wall, because that is what they are tracking.

related issue: #167

**Comment by bastianilso** [comment]
Could be e.g. 

![image](https://user-images.githubusercontent.com/3967945/193755607-decb5aee-5840-4f8d-bb79-99c12fce8e92.png)

**Comment by bastianilso** [comment]
Alternative: tile wall. So cursor can never exceed boundaries. Going left means cursor appears right.

**Comment by lucasmnt** [comment]
I've been working on this issue, and right know I have two version of the work, one with only one arrow, and the other with three arrows. I also managed to make the arrows appear when we are going out of vertical boundaries (not only horizontal one).

See with only one arrow :

![ArrowBoundaries](https://user-images.githubusercontent.com/94845309/195548311-a256c9c4-6300-4ae9-b8cf-ef416a8ae4fc.gif)


See with three arrows :

![ArrowBoundaries2](https://user-images.githubusercontent.com/94845309/195548395-b33a361a-2d20-4ae9-ba9c-79d09aa075f4.gif)


In any cases, these arrows are 2D sprites, and they can appear simultaneously if you are out of vertical and horizontal boundaries at the same time.

**Comment by lucasmnt** [comment]
I want to add that right now, all the code that manages the appearing of the different arrows is situated inside the WallManager.cs script, since it's the only place (that I found) where we have access to the wall dimensions, and positions. 
Is it ok to leave it here or should I try to get the logic somewhere else ?

**Comment by bastianilso** [comment]
- Rather than scaling them as a group, you could scale them individually.
- Prefab that's "BoundaryArrow" and then have an automatic animation. And then you can instantiate it X number of times.
- Make the arrows slightly smaller.

- We discussed a new proposed behavior:
1. Show a single arrow per side of the wall. If the cursor moves outside the wall, show an arrow, with orientation towards the cursor by using the `Transform.LookAt()` function.

**Comment by lucasmnt** [comment]
I was wondering if, in the same fashion as the mole prefab, we should move the logic to the BoundaryArrow prefab and not to the target (there is also the fact that there are two Targets, one for left and one for right controller).
Wall Manager will stay clean, and the only "problem" would be getting cursors positions.

Right now i'm putting the logic to the Target, but we will still need to create like a BoundaryArrow.cs am I right ?

**Comment by bastianilso** [comment]
Some ways to handle the infinite cursor challenge when going beyond the wall:

- create a 2D plan behind the wall with no visibility but with a collider, so the cursor doesn't go to infinity.
- detects when cursor positions beyond the wall (using X or Y max positions) and use this detection to determine the visibility of the arrows.

As for attaching the arrows to the person's field of view, our normal approach is to attach it to an invisible game object placed on the head. However, please make it possible to switch between using FOV arrows and having them attached to the wall, since we don't quiet know what is the appropriate choice yet.

**Comment by bastianilso** [comment]
current WIP branch holds the latest work in this area:
https://github.com/med-material/Whack_A_Mole_VR/tree/wip/arrow-boundaries

**Comment by bastianilso** [comment]
Implemented with commit d3b2482c5ecc3395c64f8eb654babfea7ff2d85b
