### ISSUE TITLE
Logging: CurrentMoleToHitID not updated properly in Event logs

### ISSUE THREAD

**Issue by aldsanms** [med-material/Whack_A_Mole_VR#224]
@Xav1204 @lucasmnt 
![errorEvent01](https://user-images.githubusercontent.com/73821252/199211892-8f39ef94-e3f4-4cac-90e8-b8026a2968f9.PNG)

There is a mismatch in the "CurrentMoleToHitId" column of the "log_xxx_Event.csv" file when a new mole appears on the wall.

The mole ID in the "CurrentMoleToHitId" column are updated with a delay tick.

**Comment by bastianilso** [comment]
this should be resolved now (it is intentional behavior that CurrentMoleToHitId only updates when real moles spawn, fake moles dont affect it since they are not considered current moles to hit.)
