### ISSUE TITLE
Infrastructure: Upgrade Pupil Labs HMD eyes to 1.4

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#227]
Similar to the SteamVR upgrade, we need to investigate if it is possible to upgrade our eye tracking system to the latest version, so we can benefit from improved accuracy.

@Xav1204 can you check whether it's possible for us to upgrade to the latest version of Pupil Labs HMD-eyes plugin?

https://github.com/pupil-labs/hmd-eyes/releases

I would like you to test also whether eye tracking still works:
- Testing the eye tracking by using the "GazeDemo" provided with Pupil Labs.
- Testing eye tracking and gaze recording from within Whack-A-Mole. This require that you turn eye-tracking to "On" inside the therapist panel, 
![image](https://user-images.githubusercontent.com/3967945/200516585-6e6e2a04-a84c-458f-8da0-b61dcfe9f674.png)
- while running ["Pupil Capture"](https://github.com/pupil-labs/pupil/releases/) in the background.  you can then go through the calibration procedure.

You can see how the calibration procedure works in this older video:
https://www.youtube.com/watch?v=2d5cQzJbUag

**Comment by Xav1204** [comment]
@bastianilso I've made the tests on GazeDemo and in the Whack a Mole project and at first sight, this seems correct. Indeed, the prefab are the same that the version that we have. So, we have to change anything in the mainscene. The only thing that change are variable values and code logic in two files.

**Comment by Xav1204** [comment]
https://user-images.githubusercontent.com/73820233/200781443-7a1153a7-fd46-4639-8c34-6491019cf8ce.mp4

@bastianilso The pupilLab upgrade is a success. The latest version of pupilLab works with every Unity version from the 2018.4

**Comment by bastianilso** [comment]
resolved with #231
