### ISSUE TITLE
LoggingManager : Bug with Meta csv file

### ISSUE THREAD

**Issue by Xav1204** [med-material/Whack_A_Mole_VR#234]
When we've created the new multi saving system, a bug appeared in the meta csv file.
So, when we launch and we run a game, the first meta file looks like that : 

![image](https://user-images.githubusercontent.com/73820233/203012993-4512f455-58ab-48d8-8691-b16a61619da6.png)

However, we run a new game, the meta file looks like : 

![image](https://user-images.githubusercontent.com/73820233/203013125-47c40797-dbba-4fe7-b884-b5143ab468f9.png)

A new line appeared with multiple null value.

So, we need to investigate and find where is the problem.

**Comment by bastianilso** [comment]
@Xav1204 is this still an issue or have we solved it?
