### ISSUE TITLE
WallManager: Log position of each mole on creation time

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#235]
Currently WallManager logs its extremities and each mole logs its position whenever it is interacted with. This is fine if all moles are interacted with or if the moles are vertically/horizontally aligned. However, any of these assumptions may break if some moles dont activate during the game or if we later apply some jitter/random noise to the mole's locations (which is a feature which has been requested in issue #171). Visualization tools which rely on visualizing positions of all moles on the wall therefore cannot be certain about unactivated mole's locations.

To address this issue, it might be most future-proof if for each mole, the WallManager on Wall Generation reports to LoggingManager a `Mole Created` event, along with the mole's `MoleIndexX/Y` and `MoleWorldPositionX/Y/Z`.

**Comment by Xav1204** [comment]
@bastianilso The informations of each moles need to log in a specific csv file ?

**Comment by Xav1204** [comment]
[log_2022_11_29_10_47_39_3266_Event.csv](https://github.com/med-material/Whack_A_Mole_VR/files/10111797/log_2022_11_29_10_47_39_3266_Event.csv)

@bastianilso I have saved the information in the event csv file for the moment. Can you tell me if this is the result you were expecting?

**Comment by bastianilso** [comment]
@Xav1204 yes, this is what I was expecting.

**Comment by Xav1204** [comment]
@bastianilso great. For this system, we have two options.

1. We can use a reference to loggingManager in wallManager.
2. We can use an UnityEvent to send mole Information from wallManager to loggingManager.

Which option do you want to implement ?

**Comment by bastianilso** [comment]
resolved with merge of #236
