### ISSUE TITLE
Pointer: Overhaul

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#24]
The current behavior in Whack-a-Mole VR allows the player to hold down the Controller Trigger and shoot for an infinite amount of time. This makes it possible for instance to hold the trigger and drag across the screen, shooting all the moles without releasing.

We should instead enforce a duration threshold - so that the laser is more like a "shot" (but not projectile) - we could show the laser fully opaque for a brief while (0.1s), and fade it out (0.9s).

**Comment by bastianilso** [comment]
We will also need a "Out of juice" time. Lets try with 0.5 seconds - try and see what feels right, to discourage you to spam the trigger.

See for instance how the MPG works in Stickman Warfare:
https://youtu.be/7nlAszLP4eo?t=51

**Comment by QuentinDaveau** [comment]
> The current behavior in Whack-a-Mole VR allows the player to hold down the Controller Trigger and shoot for an infinite amount of time. This makes it possible for instance to hold the trigger and drag across the screen, shooting all the moles without releasing.
> We should instead enforce a duration threshold - so that the laser is more like a "shot" (but not projectile) - we could show the laser fully opaque for a brief while (0.1s), and fade it out (0.9s).

The laser should currently already behave like a shot, if I'm not mistaken. If that's not the case, this would mean there is a bug in the code.

> See for instance how the MPG works in Stickman Warfare:
https://youtu.be/7nlAszLP4eo?t=51

Should the trail left by the laser in the example be integrated in issue #3 ?

**Comment by QuentinDaveau** [comment]
Due to last conversation, updating the issue as "Pointer: overhaul". This issue is now about the multiple improvements that can be made on the pointer.

**Comment by QuentinDaveau** [comment]
The current improvements that needs to be made:

- The cooldown needs to be improved.
- The laser should by default be thinner and have a more neutral color (white/gray, transparency ?)
- On shoot: if an activated Mole is hit, green laser, otherwise (hit nothing or fake Mole), red laser (variance between fake/nothing ?)
- On shoot: increase the width of the laser (visual feedback).
- Laser material should emit light

Issue related to #3

**Comment by QuentinDaveau** [comment]
Concerning the laser light emission, it is good to note that using an emissive material doesn't light up other objects unless the lighting object is static, which is not the case with the laser. It is however possible to place a simple point light on the "cursor" (object placed at the tip of the laser), to get a lighting effect.

**Comment by QuentinDaveau** [comment]
Issue fixed with pull request #31. Closing the issue.
