### ISSUE TITLE
Left laser position is missing in sample.csv

### ISSUE THREAD

**Issue by aldsanms** [med-material/Whack_A_Mole_VR#245]
@Xav1204 

The following columns are missing from the sample.csv file:

- LeftControllerLaserPosWorldX
- LeftControllerLaserPosWorldY
- LeftControllerLaserPosWorldZ
- 
I need it for my visualization.

**Comment by Xav1204** [comment]
@aldsanms you can test with the following files. Tell me if it's not right.
[CSV.zip](https://github.com/med-material/Whack_A_Mole_VR/files/10535524/CSV.zip)

**Comment by aldsanms** [comment]
> @aldsanms you can test with the following files. Tell me if it's not right. [CSV.zip](https://github.com/med-material/Whack_A_Mole_VR/files/10535524/CSV.zip)

Hey,

I'm fixing some bugs in my program, but I have a few questions:

- is "DistractorLeft Mole Expired" and "DistractorLeft Mole Spawned" in the event column the same as "Fake Mole Expired" and "Fake Mole Spawned" on your previous version?
- Why "left" on "DistractorLeft Mole..."? I never see "right"

**Comment by aldsanms** [comment]
@Xav1204 

I have in your last CSV, in "ControllerName" column in event.csv file, it's null all the time. I need it to know if I should show motion or not.

**Comment by Xav1204** [comment]
@aldsanms Yes, Distractor Mole Spawned/Expired are the same as Fake mole in the previous version.
We have Distractor Left and Right, it's probably that no Distractor Right spawned during this session.
![image](https://user-images.githubusercontent.com/73820233/215986437-a82fdeba-e513-4d99-af9b-c7e82868fc94.png)
For the controller name, it appears when you hit a mole to specify with which controller you hit the mole.

**Comment by bastianilso** [comment]
@aldsanms in the Event column, there is the "Controller Main Set Both" field. Maybe looking for this value is a better indicator of which controllers are currently active.

@Xav1204 maybe we should emit a "Controller Main Set Right" on startup of Whack-A-Mole, since this is the default value?

**Comment by aldsanms** [comment]
@Xav1204 

Can you send me the CSV of a more complete game with head movements and mole interaction?

**Comment by Xav1204** [comment]
@aldsanms you can try with these files to see if it's right.
[CSV.zip](https://github.com/med-material/Whack_A_Mole_VR/files/10555942/CSV.zip)

**Comment by aldsanms** [comment]
> @aldsanms you can try with these files to see if it's right. [CSV.zip](https://github.com/med-material/Whack_A_Mole_VR/files/10555942/CSV.zip)

Everything works fine with these files. thank you.

**Comment by aldsanms** [comment]
I think this issue can be closed.

**Comment by bastianilso** [comment]
Controller state along with other modifiers are now announced with every game start as per commit 11924a120d637124de46354dba577c29faaa0638
