### ISSUE TITLE
Logger: further mole logging improvements

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/Whack_A_Mole_VR#25]
In data analysis on how well patients perform we need to be able to identify three different types of events regarding hitting moles (hit moles, missed moles aka hit attempts, expired moles)

1. expired moles should be different from 'mole missed'. Mole missed should indicate an attempt to shoot the laser at the screen but no mole being hit by it.

1. for expired moles we would need the time since it was spawned as a column 'MoleTimeSinceSpawn'

1. we can use the same column for specifying how long it took people to hit a mole from the point in time when it spawned. The current solution of parsing the log backwards will create problems and dependencies when we make further changes e.g. having multiple moles available on the screen for hitting. This is also a convenience parameter for fast analysis.

1. for missed hits we need to know the x,y distance to the closest mole. Given that someone can fire the laser 'at the same time' that the mole disappears it would be good to report the x,y offset to the closest mole (within the last second). Rather than implementing a floating window that keeps track of moles during the last x seconds including their positions it would make more sense to change the mole behaviour/appearance. Moles can be either visible or expired (they can be still hit and report their position but they are not visible to the users and there's no feedback of them being hit. The feedback to the shooting for expired moles should be the same as if the person shoots and misses a mole or there's no mole in the first place).

1. we also need the x y distance  from the center of the mole to the intersection of the laser with the target (mole). We need that both in world space and local space. See issue #26

**Comment by QuentinDaveau** [comment]
@hendrikknoche 
> expired moles should be different from 'mole missed'. Mole missed should indicate an attempt to shoot the laser at the screen but no mole being hit by it.

Okay, seems good to me. I'll implement it.

> for expired moles we would need the time since it was spawned as a column 'MoleTimeSinceSpawn'

Do you mean how long it has been activated ? If that's the case it is already logged as "Mole Life Time".

> we can use the same column for specifying how long it took people to hit a mole from the point in time when it spawned. The current solution of parsing the log backwards will create problems and dependencies when we make further changes e.g. having multiple moles available on the screen for hitting. This is also a convenience parameter for fast analysis.

Same as previous, if you mean the time since it was spawned before being hit, it is already being logged as "Mole Activated Duration"

> for missed hits we need to know the x,y distance to the closest mole. Given that someone can fire the laser 'at the same time' that the mole disappears it would be good to report the x,y offset to the closest mole (within the last second). Rather than implementing a floating window that keeps track of moles during the last x seconds including their positions it would make more sense to change the mole behaviour/appearance. Moles can be either visible or expired (they can be still hit and report their position but they are not visible to the users and there's no feedback of them being hit. The feedback to the shooting for expired moles should be the same as if the person shoots and misses a mole or there's no mole in the first place).

Okay, I'll implement it.

> we also need the x y distance from the center of the mole to the intersection of the laser with the target (mole). We need that both in world space and local space.

Has been implemented with issue #26, but only as local position. Global position doesn't seem to make much sense since the moles are rotated all around the player, so unless we also log the rotation of the Mole, I don't see how this data can be used. However I can still add it to the log anyway, let me know what are your thoughts about it.

**Comment by QuentinDaveau** [comment]
@hendrikknoche 
> for missed hits we need to know the x,y distance to the closest mole. Given that someone can fire the laser 'at the same time' that the mole disappears it would be good to report the x,y offset to the closest mole (within the last second). Rather than implementing a floating window that keeps track of moles during the last x seconds including their positions it would make more sense to change the mole behaviour/appearance. Moles can be either visible or expired (they can be still hit and report their position but they are not visible to the users and there's no feedback of them being hit. The feedback to the shooting for expired moles should be the same as if the person shoots and misses a mole or there's no mole in the first place).

What I did is that I added a new event in the logs (`Expired Mole Hit`), which is raised if an expired Mole (a Mole which just passed from the enabled to the disabled state) is hit. A Mole stays in the expired state for a very short time (can be set in the editor, right now it is 0.2 seconds) before entering in the disabled state. 
With the `Expired Mole Hit` event comes five new log entries: `ClosestActiveMoleDistance`(X, Y) which corresponds to the distance between the hit point and the closest active Mole, on the X and Y axes, and `HitPositionWorld`(X, Y, Z) which corresponds to the current hit position in world coordinates and on the X, Y and Z axes.

What do you think about this implementation ? Should I add/change things or is that good enough ?

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of #32. Closing the issue.
