### ISSUE TITLE
Add Parameter to Therapist UI for Changing OutOfBound Indicator Type

### ISSUE THREAD

**Issue by tcaruchet** [med-material/Whack_A_Mole_VR#255]
This issue aims to improve the user interface by providing therapists the ability to easily change the type of OutOfBound indicator used during sessions. This will require adding a new parameter option to the therapist's navigation pane. 

**Requirements:**

0. **Learn Codebase**

1. **New UI Element:** Add a new option in the therapist's navigation pane. This could be implemented as a radio button group that allows the selection between different OutOfBound indicator types (like the others parameters). The options should include at least "Static Pointing" and "Pointing Center".

2. **Updating Indicator Type:** The selection of the indicator type in the therapist UI should directly update the `BubbleDisplay`'s `outOfBoundIndicatorManager` to use the selected OutOfBound indicator. This will require creating a public method in the `BubbleDisplay` class to handle this (creates as : `public void ChangeIndicator(ArrowType arrowType)`).

3. **Save Indicator Type:** The chosen OutOfBound indicator type may be saved as part of the session's settings, ensuring it persists between different sessions and upon application restart ?

4. **UI Updates:** The UI should update in real-time to reflect the currently active OutOfBound indicator.

The goal of it is to studying what type of indicators is the most clearly and intuitive for the user (in a context of an interview, for example).

**Comment by bastianilso** [comment]
Hi @tcaruchet ! Thanks for this issue.

Currently the scope of the OutOfBound indication, is that we are going to use it first and foremost for scientific purposes (studying human behavior) in an experiment. Based on our study we can then see whether we wish to introduce it as a control for clinicians too (and how). We can use the issue to track the progress on this. 😊

So i think as a starting point, we may want the the OutOfBound indicator type exposed as a game modifier through the `ModifiersManager` and make it possible to control from treatment programs `.wampat` files, by implementing support for reading the type from the  `PatternInterface`.

**Comment by tcaruchet** [comment]
Closing because it's not necessary for now and for the study.
