### ISSUE TITLE
Mole: Use 2D Flat Circle, Instead of 3D Sphere

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#26]
When people hit moles, they are not seeing all of the geometry of each mole - because the moles are 3D, they stick out of the wall, which exposes some parts more than others. For the purpose of diagnosing neglect in patients, we need to track where on each mole, the patient shot their laser (see issue #25).

Therefore it would be better to keep the moles as flat circles, where we can in their local space track X and Y (with center being (0.0)).

**Comment by QuentinDaveau** [comment]
@bastianilso what would be the best name for the log, "MoleHitLocationX", "MoleHitLocationY" ?

**Comment by bastianilso** [comment]
@QuentinDaveau MoleSurfaceHitLocationX / Y maybe?

**Comment by QuentinDaveau** [comment]
Issue fixed with pull request #29. Closing the issue.
