### ISSUE TITLE
Game: Improve wall generation

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/Whack_A_Mole_VR#28]
Currently the Moles are placed on the wall following a x^2 curve, squashed by the curveCoeff variable:

![image](https://user-images.githubusercontent.com/45624296/68378429-64e39480-014c-11ea-93f3-c52d432e1ccc.png)

This gets pretty close to the cylinder, however an elliptic curve would be better:

![image](https://user-images.githubusercontent.com/45624296/68378603-ad9b4d80-014c-11ea-829c-cacbddd1d27c.png)

This pauses an issue concerning the placement of the Moles following the curve. Currently the moles are placed every x step (x = 0, x = 1, x = 2...). This means that, the higher the edge of the curve (its tangent's value for a given point), the higher the distance between the moles:

![image](https://user-images.githubusercontent.com/45624296/68379196-ba6c7100-014d-11ea-8c7c-e1a0a380d2a9.png)

This issue isn't too much present with the current squared curve, however it is pretty obvious with the elliptic curve. It would be necessary to either change the way the moles are placed (maybe by placing spawn points by hand like how it's done in the old version), or manage to take it into account when placing the moles (forcing the same distance between moles using a cos/sin ratio).

**Comment by bastianilso** [comment]
That would definitely be an improvement. Is it possible to generate the wall "flat", position the moles, and  then apply the elliptic curve afterwards, whilst the moles are parented to this wall?

**Comment by bastianilso** [comment]
@QuentinDaveau some information from our collaborator:

> From a clinical perspective the moles should appear to be evenly distributed with similar distance between them and at approximately same reaching distance.

I think to get as close to this as possible, we should go for the elliptic curve and somehow ensure equal apparent spacing between moles.

Some additional behavioral remarks from me:

- I think we should aim to have all moles generally visible within field of view, if one were to look straight onto the center in the HMD. Could you try to position/scale the wall like the pictures below?

![image](https://user-images.githubusercontent.com/3967945/68479145-eeb95d80-0231-11ea-8ed2-3a08cf5fade0.png)
![image](https://user-images.githubusercontent.com/3967945/68479166-fda01000-0231-11ea-8ae8-679099892f81.png)

**Comment by QuentinDaveau** [comment]
@bastianilso 

> I think we should aim to have all moles generally visible within field of view, if one were to look straight onto the center in the HMD. Could you try to position/scale the wall like to imitate that, a bit like im trying to demonstrate in the pictures below?

Okay so we are facing some issue with that:

- The field of view in the headset is a circle, while the wall is generated as a rectangle, meaning that the Moles in the corners are always out of the field of view if the participant looks straight at the center of the wall. Removing them could be a simple solution to fix this issue.

- The cylinder model needs to be redone to have a different curvature (less curved), since it differs too much from the player position when it is pushed back (half a circle, which is the current cylinder shape, is too much unless the player is close to it). Maybe generating the cylinder mesh at runtime would be a good solution. Like that we would always have a cylinder model that fits the Moles placement following the given parameters.

- It is important to keep in mind that the FOV in the headset is really low compared to the real FOV of an human eye. Using a higher FOV in Unity is possible, but it is not recommended since it can cause dizziness and that the placement of the objects will differ between the game and the reality (the controllers will seem further that they really are).

**Comment by QuentinDaveau** [comment]
@bastianilso 

Right now we also have an issue because of the cylinder shape. Either we need to cut off a big piece of the angles so the view fits with the center of the cylinder, or we need to leave a blank space in the center to include the angles. This is due to the Moles not being curved on the Y axis:

![image](https://user-images.githubusercontent.com/45624296/69055763-da821700-0a0e-11ea-85cb-6ec2705bebfb.png)

Maybe it would be better to have a "dome" as wall:

![image](https://user-images.githubusercontent.com/45624296/69055195-83c80d80-0a0d-11ea-8f83-3903d3514065.png)

Like that the Moles would be at the same distance to the player on every axis, and it would better fit with the circular FOV seen by the player through the Vive.

**Comment by bastianilso** [comment]
@QuentinDaveau great analysis of this problem. 🎅  Yes, let's try with the dome representation. And I agree, there would have to be a large padding between the outer boundary of the dome and where the moles start appearing.

Alternatively, it could be a dome which is relatively flat (given the low FoV) (so almost not curved).

**Comment by QuentinDaveau** [comment]
@bastianilso quick preview of the wall generated at runtime:

![image](https://user-images.githubusercontent.com/45624296/69072454-f811a980-0a2b-11ea-9eca-604cc66bd358.png)

It is generated depending on the Mole placement. It is far from being perfect but I think it will be way better than using a premade model.

**Comment by QuentinDaveau** [comment]
> quick preview of the wall generated at runtime

I'll make it its own issue, since this issue is related to the curving of the wall.

**Comment by bastianilso** [comment]
@QuentinDaveau very cool. If we go parametric, perhaps it would be possible to create sliders to adjust the curvature - between flat and curvy, so we can make adjustments from the Unity Inspector later.

**Comment by QuentinDaveau** [comment]
New generation of the wall, now with the possibility to apply a curvature on the Y axis too:

![image](https://user-images.githubusercontent.com/45624296/69133469-3c498c00-0ab6-11ea-8709-eeb814783ba7.png)

The edge moles are now cropped. There are many sliders in the editor to customise the wall:

![image](https://user-images.githubusercontent.com/45624296/69133554-60a56880-0ab6-11ea-81f8-83808a9447ec.png)

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of pull request #37. Closing the issue.
