### ISSUE TITLE
Improve visual feedback when triggering 

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#3]
Currently we are missing feedback when triggering moles. It would be nice if the moles lit up when triggered and indicated by light color whether the user performed the right choice. See illustration below.

![light-up-wrong-correct](https://user-images.githubusercontent.com/3967945/60020058-82c5c680-968f-11e9-8c99-c1477c810459.png)

**Comment by QuentinDaveau** [comment]
May be linked to issue #18. Good sound effects can be really useful for a good feedback.

**Comment by QuentinDaveau** [comment]
Good reference:
https://www.gdcvault.com/play/1016487/Juice-It-or-Lose

**Comment by QuentinDaveau** [comment]
Suggestions on juice:

Mole: On hover, slight expansion of the Mole. On hit, quickly shrink and comes back to normal size, or maybe elastic effect (https://easings.net/#easeOutBack, https://easings.net/#easeOutElastic). I think an elastic effect can be really great. On hover, the color of the Mole switches to a "highlight" color, on hit it switches to a "hit" color (already implemented).

As sound, using a "Dong" sound when a Mole is hit (different between correct and incorrect hit, maybe with highter tone for correct hit) could really reinforce the "hitting something" feeling ( for example, correct: https://freesound.org/people/Daphne_in_Wonderland/sounds/127150/, disabled: https://freesound.org/people/Adam_N/sounds/164573/, wrong: https://freesound.org/people/sangtao/sounds/190929/)

**Comment by QuentinDaveau** [comment]
Comments from #31:

- Shooting a target should turn the mole completely white.
- Making the mole "bubble in", ie, make it move backwards and forward again in response to the shot. A bit like hitting a button.

**Comment by bastianilso** [comment]
here is a visual mockup of what we mean by hitting a button, see gif below:
![007](https://user-images.githubusercontent.com/3967945/68742525-ac589d80-05f0-11ea-8cdb-00f467ced5c2.gif)

**Comment by QuentinDaveau** [comment]
@bastianilso a quick test of the Mole hit animation:

"Bubble" animation:
![Mole_bubble_animation](https://user-images.githubusercontent.com/45624296/68770847-34f23080-0627-11ea-9583-a07edddb46cf.gif)


"Spring" animation:
![Mole_bounce_animation](https://user-images.githubusercontent.com/45624296/68770857-37ed2100-0627-11ea-8db4-f8698ac8b3fe.gif)

Both are 0.4s long. Honestly I prefer the spring animation :D. Anyway, we'll need to try these animations while playing the game to really see how they feel.

**Comment by bastianilso** [comment]
@QuentinDaveau cool, spring looks good too :+1:

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of pull-request #33. Closing the issue.
