### ISSUE TITLE
Game: Generate wall at runtime

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/Whack_A_Mole_VR#34]
Currently the wall is a 3D model made in blender. This is quite inconvenient to work with and it prevent us from modifying the wall. Generating a wall at runtime depending on the Mole's position would be easier to work with and way more polyvalent. We could, for example, use multiple types of walls.

**Comment by bastianilso** [comment]
@QuentinDaveau would be good. I suggest that the wall is given a certain thickness too. Also, we need to ensure that it has enough polygons, so as to appear round and smooth. 🐎

**Comment by QuentinDaveau** [comment]
@bastianilso 
The new wall generated with a curved generation from #28:

![image](https://user-images.githubusercontent.com/45624296/69138512-212f4a00-0abf-11ea-807a-61de8daf482e.png)

I don't think I can do better concerning the wall generation though. Currently the wall is a plane with texture on only one side, but I don't think this would be an issue since the player isn't supposed to go behind the wall:

![image](https://user-images.githubusercontent.com/45624296/69138744-7ff4c380-0abf-11ea-9b08-7d0581acb41c.png)

Normally with a wall like that the Mole shouldn't clip through it when playing its animation, I need to test it in VR to confirm it.

**Comment by bastianilso** [comment]
Looks very nice. Yea, one thing we could do is to make a hybrid combination of a 3D model and 3D generated wall. Ie. Any decorative elements could be parented to the wall and positioned at the boundaries. Anyway, for now let's start with this, I think its a good starting point to iterate from.

**Comment by QuentinDaveau** [comment]
> Any decorative elements could be parented to the wall and positioned at the boundaries. Anyway, for now let's start with this, I think its a good starting point to iterate from.

That's a pretty good idea, I agree that's an issue for another time :D. I'll create an issue for it, so we don't forget.

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of pull request #37. Closing the issue.
