### ISSUE TITLE
Visuals: Correct Colors

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#36]
Currently the colors in the game don't create a cohesive use of values and saturation. The below mockup suggests a color scheme and uses a motive based on the new wall generation discussed in #34 . The color scheme adheres to the existing established conventions, but the colors were adjustment in terms of value and saturation. See mockup and suggested colors below:

![image](https://user-images.githubusercontent.com/3967945/69149677-4af46b00-0ad7-11ea-818a-f9f1555efe19.png)
![image](https://user-images.githubusercontent.com/3967945/69150359-d8848a80-0ad8-11ea-817e-5744ded4bc7b.png)

In later stages we might want to go for an alternate scheme (ie. pure gray-scale, to keep it more "clinical"), but lets use this as a starting point.

EDIT: The apparent distance to the wall should not be considered here (just a mockup), its mainly establishing a color scheme.

**Comment by QuentinDaveau** [comment]
That's pretty interesting. Which kind of convention does this color scheme follows ? Material design ?

**Comment by QuentinDaveau** [comment]
The UI (player panel, therapist panel) is currently white (ffffff). Is that good ? It may blend with the wall/skybox horizon.

**Comment by bastianilso** [comment]
@QuentinDaveau self-invented color scheme. But yea, its not realism, its more of a playful simplification. The end goal is to obtain a more clinical feeling to it - in the end what matters is that patients/therapists from an outlook will see this as a tool for diagnosis, rather than a game (although it should retain its motivating/playful qualities).

Good point about the overlay UI. We might want to add a thin grey border on the left-hand side.

**Comment by QuentinDaveau** [comment]
@bastianilso some feedback after implementing the new color scheme:

- In the end the elements don't blend that much with the skybox, which is good. The overall color scheme feels great too.

- One concern is the "aggressiveness" of the colors, which are really bright and can put a strain on the eyes after prolonged use. Already after using the headset for one minute it feels a bit unpleasant. Tuning down the brightness of the colors a bit may be a good solution.

**Comment by bastianilso** [comment]
@QuentinDaveau very nice. I just passed by to test, but we didnt get the colors working yet - but lets do that test later.

Eye strain is definitely a valid issue. I have reviewed SteamVR's default color scheme a bit and they employ some interesting rules to their color scheme.
![image](https://user-images.githubusercontent.com/3967945/70439567-a4c1d280-1a90-11ea-9445-f2c80a1cf81b.png)

- Any background elements (3D elements, even interactable ones) in the steam house employs at maximum 232/255 brightness and at most 128/255 saturation.
- foreground elements (UI elements) use the full scale: 0-255.

I will investigate applying the same constraints to our color scheme.

**Comment by bastianilso** [comment]
Here's a quick update:

![image](https://user-images.githubusercontent.com/3967945/70444125-b065c700-1a99-11ea-8c3b-632fd0636cf7.png)
![image](https://user-images.githubusercontent.com/3967945/70444249-e3a85600-1a99-11ea-90a4-d6bfd7daef89.png)

I think one of the main eye sores in VR was looking at the black moles - here's a toned down version of that. The wall color is mostly the same - everything else has received adjustments in terms of tone/sat though, in many case bringing values closer to each other (lowering contrast).

**Comment by QuentinDaveau** [comment]
@bastianilso I'll implement the new colors. 
Concerning the shadow projected by the wall on an invisible plane, I can't manage to find a working shader. There are plenty, but almost all of them are for old Unity versions. Some seems to work but only in the editor, I think SteamVR changes some camera rendering settings at runtime which breaks the shader when rendering.

One solution would be to simply place a visible plane but with the exact same color as the skybox's ground. However the environmental lightning pauses problem in this case, so we may want to disable it too. This may work but it is a bit sketchy. I'll try some other stuff, I'll keep you in touch.

**Comment by hendrikknoche** [comment]
Martin Kraus in the department is an expert in shader programming and Unity. He would know.

**Comment by QuentinDaveau** [comment]
Some feedback concerning the new color changes:

- It's better on the eyes, however the Moles are a bit too bright and tend to blend with the wall. Setting their color a bit darker would be good.

- Due to the wall brightness, the white laser is less visible. I think darkening the wall just a bit might be good too.

- Concerning the shadow, unless we create a true floor, I don't think it will be manageable. Having a true transparent object receive shadow is possible, but is prone to bugs and ressource intensive so I think it's not the best solution. I also tried to blend an opaque object with the skybox's color (so it is hidden) but without success. One possible solution could be to use a shader displaying the skybox behind the object to create a fake transparency all while keeping the object opaque. However I don't know if it is manageable or not.

Feel free to pass by to test the new color scheme in VR.

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of #46. Closing the issue.
