### ISSUE TITLE
Update README.md with new screenshots

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#39]
Would be great with new pictures of Whack-a-Mole in its current state in the README.md file. It should mainly cover:
- The motivation behind the whack-a-mole project. 
- The intended use cases and audience.
- Bullet points with key features (play at different speeds, apply modifiers, features to perform experiments)
- Description of the connection to the R shiny application with a link to it.
- A technical section on the data collection / what data is collected / explanation of what the columns means (which we already have).

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of #44. Closing it.
