### ISSUE TITLE
Revamp Whack-A-Mole Main Menu

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#4]
The Main menu is currently implemented using Box Colliders. Additionally, it implements an undesired and unnecessarily complex visual design. Instead, let's aim for implementing the design below:

![whack-a-mole-ui](https://user-images.githubusercontent.com/3967945/60025106-4303dc80-9699-11e9-83ac-8b4d09f37a8d.png)

- [ ] Remove the wooden texture
- [ ] Remove Difficulty Selection and put it inside the Unity Editor instead.
- [ ] Use Source Sans Pro Font, and change font sizes appropriately as in the image (and add attribution to our README).
- [ ] Show instructional pictures and text to the participant.
- [ ] Show a green start button which the participant must interact with to start the game.
- [ ] Show Game Duration, Participant Number and Test number at the bottom using the symbolics from the Google Material Design Icon set (add appropriate attribution in our README).

**Download Assets Here:**
[whack-a-mole-ui-assets.zip](https://github.com/med-material/Whack_A_Mole_VR/files/3321198/whack-a-mole-ui-assets.zip)

**Comment by QuentinDaveau** [comment]
Linked to issue #17

**Comment by QuentinDaveau** [comment]
Issue fixed with merge of #22. Closing it.
