### ISSUE TITLE
Logs: Add extra convenience fields

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/Whack_A_Mole_VR#40]
We could add some extra fields in the logs to simplify data visualisation and filtering. Here are my suggestions:

- Add a "eventType" field, which could be used to identify what is the type of the event (mole event, game event, modifier event). This could really ease data filtering.

- If we plan to have multiple wall geometries, we may want to log it in a way. We may also want to add universal properties for the moles which could be used whatever the wall shape. In consequence we may want to add "wall logs" (wall width, height, Xcurvature, Ycurvature, row count, column count) and new Mole logs (normalized index X, normalized index Y). Normalized mole indexes could be used to compare Mole data across multiple wall shapes.

- Maybe separate the date and time fields. SQL is supposed to support seconds and milliseconds in its "datetime" format, but is doesn't seems to work in our case (need to update the server ? some property to set ?). Anyway, we don't seem to use the field as a whole, since most of the time we either want just the date, or just the time (hour, min, seconds...). I propose we keep a "DateTime" field containing the date + time, but we also add a "Date" field containing only the date and a "Time" field containing only the time. This way gathering data would be much simpler.

**Comment by bastianilso** [comment]
I think all your suggestions are good - feel free to add these columns. 🏭 
@hendrikknoche do you have any comments?

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of pull-request #41. Closing it.
