### ISSUE TITLE
Pointer: Add Smoothing Parameter to Pointer Movement

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#45]
Currently the pointer has high sensitivity to movement - this causes the laser to appear "stuttering" when it is used in practice in Whack-a-mole. It would be nice if we could adjust the pointer's sensitivity to movements, to obtain a smoother behavior, but without creating too much latency.

**Comment by QuentinDaveau** [comment]
If you are referencing the video, please note that Maxime, who is the player in the video, has dysgraphia and dyspraxia (genetic illness which makes your hand shake). That's why the pointer is shaking like that. In a normal case the "stutter" isn't present, however it is true that a smoothing option could prove useful for people with shaky hands (old people...)

**Comment by QuentinDaveau** [comment]
Shouldn't we also try to implement some form of "snapping" ? The laser would snap to the closest Mole in a certain range, or maybe get magnetized to the Mole (tend towards the Mole the closest it is to it).

**Comment by QuentinDaveau** [comment]
I propose three kind of "aiming assistance":
- Smoothing: a simple smooth of the laser's movements. Might create a small delay in the laser's movement but would be great to dampen small, shake-induced movements;
- Snapping: a snap of the laser directly at the center of the closest Mole (if the laser is at a certain range of any Mole). For patients who really have a hard time aiming at the Moles.
- Magnetizing: the laser tends towards the center of the closest Mole (if the laser is at a certain range of any Mole). The closest the Participant actually points to the center of the Mole, the closest the laser tends to the center of it (dunno if it's clear enough). This would be great for patients who are precise enough to point at the desired Mole but have a hard time aiming to its center (near miss the Mole).

**Comment by bastianilso** [comment]
@QuentinDaveau I think the proposals are good.

Another aspect we can look into is to simply to create bigger colliders for moles, than their physical representation. With bigger colliders and Smoothing, the advantage is that we still keep an exact mapping of where people point, to where they perceive to be pointing, while being graceful to error.

We could still in the future introduce snapping/magnetizing under the name of "aiming assistance". For experimental purposes, we are less interested in snapping/magnetizing, since part of what we are logging is how far away from the center, the patients are hitting. But for therapy/game experience/adaptive difficulty POV, I can easily see the usefulness of having snapping/magnetizing behavior.

**Comment by QuentinDaveau** [comment]
@bastianilso so for this issue, should I just add a smoothing option and an option to change the size of the Mole's hitboxes ? Snapping and magnetizing are close to the smoothing in their implementation, so I can try to implement them in this issue, it shouldn't be too hard.

Let me know what you prefer :D.

**Comment by bastianilso** [comment]
@QuentinDaveau sounds good. smoothing and size of hitboxes are most important but if there is an easy path over to snapping/magnetizing, feel free to implement that too. for the time being we will just keep those togglable from Unity, and not think about the therapist ui.

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of #47. Closing the issue.
