### ISSUE TITLE
UI: Add profile management

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/Whack_A_Mole_VR#54]
Currently, the profiles don't store anything and aren't of much use. To give them their purpose, we need to define the properties that they will store and how we can allow the user to manage these properties (new UI ?). Also defining the overall behavior of the profiles (what to do on loading...) and their restrictions (which property can we store ? which one can't we store ?...) would be great for future-proofing.

**Comment by bastianilso** [comment]
I think the immediate interest here would be:
- Any UI Settings: From Participant Number and Test Number to Modifiers like Mirror, Prism Offset etc. However, we don't need to store aspects like Game State (whether game was paused, and the timestamp the game was paused in). That, we will reset. Also, we dont need to store whether the UI is minimized or maximized - it should be maximized by default.

- Any Non-UI settings that either could become a UI setting in the future, or which are interesting to manipulate from an experimental perspective: Settings like amount of moles, wall curvature, etc. Exporting those to a file and loading them from a file, would allow researchers to setup advanced experiments where we manipulate the game environment between participants.

For both cases, it would be important that there it is easy to match the keyword in the profile, with the variable name in CS code.

**Comment by QuentinDaveau** [comment]
@bastianilso if we allow the profiles properties to be edited through the TherapistUI, we would need to alter the UI accordingly. If that's the case, could you provide some mockups, or at least let me know your point of view on this aspect ?

I think the best course of action would be first to define the workflow surrounding the profiles (who would use them ? how ? why ?).

For example, should the therapist define which property to save when creating the profile (with a dedicated panel where he can select which property to store and its values), or after it has been created (with a "save to profile" button on the TherapistUI which would save to the profile the current state of the modifiers for example). This also raises the questions of the modifiers not present in the UI (at least for now) like the wall curvature...

What is your vision for the profiles ?

**Comment by hendrikknoche** [comment]
I thought we should keep:
typical 'anonymized' values of the patient there: dominant hand, affected brain side, performance impaired side of the body.
Plus e.g. last wall layout, task settings etc.

**Comment by bastianilso** [comment]
> @bastianilso if we allow the profiles properties to be edited through the TherapistUI, we would need to alter the UI accordingly. If that's the case, could you provide some mockups, or at least let me know your point of view on this aspect ?

@QuentinDaveau the therapist UI would be the same - the difference is just that we listen to changes made to the UI (emitted as fx Events) and update values inside the INI file in the background either immediately or on applicationQuit() and/or when game starts/stops.

> I think the best course of action would be first to define the workflow surrounding the profiles (who would use them ? how ? why ?).

The profiles have two purposes: 1) For therapists to create a profile per patient who will train from the Therapist UI. 2) For researchers to hand-create pre-defined profile "files" with different settings applied to them, which can be deployed for running tests.

> For example, should the therapist define which property to save when creating the profile (with a dedicated panel where he can select which property to store and its values), or after it has been created (with a "save to profile" button on the TherapistUI which would save to the profile the current state of the modifiers for example). This also raises the questions of the modifiers not present in the UI (at least for now) like the wall curvature...

The Therapist UI will be completely the same, as explained the above - to the end-user, it will just seem like Whack-A-Mole "remembers" what settings were active at the time, for that given profile. Ie. If Mirror was activated during the last game for the Bastian profile, then next time Whack-A-Mole starts with Bastian Profile, Mirror is still activated (even if by default we keep it disabled).

In reality, profiles will contain more settings than just what the Therapist UI offers - this allows researchers to manipulate the game environment for testing. @hendrikknoche 's suggestions above could also be profile settings, which could be associated to a profile, to document patient characteristics - while "dominant hand" and "affected brain side" are not settings inside the game per se, they are information we would want the game to send to the database, and use during R Shiny Visualization to understand the game data better.

**Comment by bastianilso** [comment]
For example, see the mockup below:
![Screenshot from 2019-12-20 14-45-01](https://user-images.githubusercontent.com/3967945/71258809-5980ad00-2337-11ea-91a2-b04c1fb8f3f7.png)

**Comment by QuentinDaveau** [comment]
@bastianilso ok, thanks for the precision. I still think we should add a "save to profile" button, so the user can tinker with the settings without unvolontarily rewriting the profile (like how you would save a document). In the same idea, a "save as" functionality (to save the current settings in a new profile) would be great too.

Maybe we should include a "profile edition" window so the therapist can edit/create/delete properties (wether they are from the game, the editor or from outside the game) without having to do it by hand with an external editor (which would mean reloading the game to apply the new profile properties and risks of the profile being overwritten). This could also allow us to do some value check for in-game specific properties.

**Comment by bastianilso** [comment]
@QuentinDaveau the therapist will never touch the files - the files are a technical feature which are meant only for researchers to manipulate for designing scientific experiments.

Concerning your point on unvoluntarily rewriting the profile, my suggestion is that if there is something we want to do there in that space, we can for research purposes (fx remote experiment) introduce a "profile property" called `ProfileReadOnly:True` and disable all UI controls except starting/stopping the game. But by default (in the therapist case), we definitely want the therapist's configuration to be saved automatically. In the future, we want to do better in this space by introducing "treatment programs", which are preset configurations which therapists can design in the R Shiny UI, which target certain patient symptoms. :rabbit:
