### ISSUE TITLE
Test Patterns / Game Modes for January Experiment

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#55]
It would be great to have moles appear not only randomly, but also in certain patterns.
![image](https://user-images.githubusercontent.com/3967945/71714319-ad969180-2e0d-11ea-9084-20535f730c58.png)

We can use this for two purposes:
 - In the January experiment we can verify that the data produced by the game corresponds to our anticipations - ie. to discover bugs and pecularities.
- Discussion with Lars also gave us insight that certain patterns are useful for treatment plans and diagnosis:

> As we discussed, apart from looking at training data, in future builds we could have certain predefined scripts just used for assessment, like the one-row whack-a-mole with mirrored/unmirrored x-axis in order to make some distinction on motor and sensor neglect, some dual-task paradigms as well as a systematic run through treatment methods to test individual responses.

(the picture above is my interpretation/example of his suggestion).

**Comment by hendrikknoche** [comment]
each of the above patterns should be counterbalanced (have equal occurrences) with cases in which only the left or the right targets appear. 
so for each occurrence of one of the above double targets (i.e. except for the middle one) 
we'd have 
one case in which only the target on the left appears and 
one case in which only the target on the right appears.  

The results from these three cases would need to be compared.
We could also have the two targets not appear on the same row.

**Comment by QuentinDaveau** [comment]
This issue is quite interesting. Implementing it into the game shouldn't be too hard, however it would be nice to define how the patterns are stored (in a file would be great for future proofing, like that the therapists/experimentators could create their own custom patterns), and in which kind of "format" we save them (how we would tell the game which moles to activate). I already have my ideas concerning these.

I see here two possibilities. Either I implement it in a quick and dirty way for the experiment, probably letting me some time to tackle another issue, or I implement it in a clean way, however this may take the whole week (the time to do a parser, define a format...).

Let me know what you prefer, it all depends on what you want to prioritize for the january experiment, knowing that we should focus on Unity since the R application is currently a time sink due to the SVG graphics (which need a lot of work for not much result on the short term).

**Comment by bastianilso** [comment]
@QuentinDaveau from my point of view, feel free to do so. We may still need to think of making something that can crudely confirm whether the data we collect looks as expected, but there might be time during/after the January experiment to develop the R Shiny part.

I don't know what format you are thinking about using, but my thoughts were that this file could  define a number of moles in X/Y directions, followed by what pattern the moles should appear in (possibly with how much time in-between, 0 making a mole simultaneous with another). Also, ideally we should be able to pre-bundle those definitions with the game - for now we wont expose it in the UI, but could be set from the a Profile's setting (ie. MolePattern=Treatment2).

**Comment by QuentinDaveau** [comment]
@bastianilso thanks for the answer. For the format, I thought of something a bit mode crude. Maybe a sort txt file taking the form of a timeline, where we specify which Mole we activate, then a "waiting duration", then the next action we want to do... Maybe something like this (I added some space for visibility):

```
WALL { ROWCOL = (10,10) }
ON { MIRROR, TIME = 2, MOLE = [(2,4), (8,8)] }
ON { MIRROR, FAKE, TIME = 2, MOLE = [(2,5), (3,3)] }
WAIT [1]
SPEED { FAST }
```

The first word defines the action (`WALL` = set the wall, `ON` = activate some moles, `SPEED` = set the speed...). Then, we precise the parameters between `{}` (`MIRROR` = mirror the Mole placement, `TIME` = Mole activation duration...). Lists are between `[]` and vectors are between `()`.

With this kind of format it should be possible to set almost any parameter of the game, plus parameters outside of it.

Of course this example can be simplified for now, but I think it can work quite well on the long term. Let me know what you think of it and if you want me to work on something else before.

**Comment by bastianilso** [comment]
Nice initial draft - I think we can simplify this further.
```
WALL=(10,10) // defines 10 rows and 10 columns
MOLE=(X = 8, Y = 2, STARTTIME = 2, LIFETIME = 1) //defines that a mole should be shown at X=8, Y=2 with startTime=2, lifetime = 1
MOLE=(X = 2, Y = 2, STARTTIME = 2, LIFETIME = 3) // defines another mole, at a different location which also starts at 2 seconds, with lifetime = 3
MOLE=(X = 2, Y = 2, STARTTIME = 10, LIFETIME = 2) // defines a third mole, at startTime 10 seconds. this now creates some interval where there are not any moles.
DISTRACTOR=(...) // defines a distractor
```
`MIRROR`, and `SPEED` won't be needed . The Speed will be defined by the Profile Chosen (Medium Speed makes the time values absolute, Fast, makes it x2, Slow, makes it x0.5).  And Mirror can be implemented by spawning two moles manually at the respective coordinates - just to keep things simple.

**Comment by QuentinDaveau** [comment]
@bastianilso Ok, let's keep things simple then :D 

I'll implement a first version to see what it gives, I'll keep you in touch.

**Comment by QuentinDaveau** [comment]
Some thoughts for possible improvements of the patterns (to be done later of course):

- One awesome thing would be to call a pattern from another pattern. Like that we could have simple patterns (activate moles in a symetric way for example) which would be called in more complex patterns. 

- It would be also great to be able to set some random values inside the patterns, for example if we want to spawn mirrored moles with a random position on the Y axis. The random value would be stored in a variable on the game side so it can be reused through multiple calls (`RAND` = access the random value, `GENRAND(start = 0, stop = 10)` = regenerate the random value to get a rangom number between 0 and 10).

**Comment by bastianilso** [comment]
Here is an example pattern, that we would want to test in one condition for the January experiment next week (this is an extended version of what I illustrated in the figure 1).
```
WALL=(ROW = 1, COL = 10)
MOLE=(X = 1, Y = 1, STARTTIME = 2, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 2, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 6, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 6, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 10, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 10, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 14, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 14, LIFETIME = 4)
MOLE=(X = 5, Y = 1, STARTTIME = 18, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 18, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 22, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 22, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 26, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 26, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 30, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 30, LIFETIME = 4)
MOLE=(X = 1, Y = 1, STARTTIME = 34, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 34, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 40, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 44, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 48, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 52, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 56, LIFETIME = 4)
MOLE=(X = 5, Y = 1, STARTTIME = 60, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 1, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 68, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 72, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 76, LIFETIME = 4)
MOLE=(X = 5, Y = 1, STARTTIME = 80, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 84, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 88, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 92, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 96, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 100, LIFETIME = 4)
```

I'm wondering whether, for the purpose of data analysis (ie, so conditions dont differ visually, except what moles get activated), want to keep the Wall actually with the same row and columns of moles at all times - and then simply only activate the center-line of moles instead.  But in any case, we could always enforce that through this format.

@QuentinDaveau your ideas about having mirror and speed in there are also good - but lets keep them for future iterations of this, for the time being. But I think it makes sense, if we think about designing treatment plans - we can use the clinical knowledge from e.g. Lars to think further about this in the future.

**Comment by hendrikknoche** [comment]
> Some thoughts for possible improvements of the patterns (to be done later of course):
> 
> * One awesome thing would be to call a pattern from another pattern. Like that we could have simple patterns (activate moles in a symetric way for example) which would be called in more complex patterns.
> * It would be also great to be able to set some random values inside the patterns, for example if we want to spawn mirrored moles with a random position on the Y axis. The random value would be stored in a variable on the game side so it can be reused through multiple calls (`RAND` = access the random value, `GENRAND(start = 0, stop = 10)` = regenerate the random value to get a rangom number between 0 and 10).



> Some thoughts for possible improvements of the patterns (to be done later of course):
> 
> * One awesome thing would be to call a pattern from another pattern. Like that we could have simple patterns (activate moles in a symetric way for example) which would be called in more complex patterns.
> * It would be also great to be able to set some random values inside the patterns, for example if we want to spawn mirrored moles with a random position on the Y axis. The random value would be stored in a variable on the game side so it can be reused through multiple calls (`RAND` = access the random value, `GENRAND(start = 0, stop = 10)` = regenerate the random value to get a rangom number between 0 and 10).

regarding the randomization: in most of these cases it's important to counterbalance the occurences of the moles - in that sense the randomization is more of random ordering of (a balanced subset of) positions. It would be not a good thing if we had the random generator create position sets that are not evenly distributed across the space.

**Comment by bastianilso** [comment]
For the January Experiment I think we will run 3 conditions then:

- 1 minute "Spreadout Pattern" without modifiers
- 1 minute "SingleRow Pattern" without modifiers
- 1 minute "Spreadout Pattern" with Mirror Modifier

Here is the Spreadout Pattern, it has the following properties:

- Looks "Seemingly Random".
- The pattern is made to test distances from highest to lowest between moles.
- The same mole is never activated more than once.
- Each region of the wall, has an equal number of moles activated (5 each). 

```
WALL=(ROW = 6, COL = 9)
MOLE=(X = 7, Y = 3, STARTTIME = 2, LIFETIME = 4)
MOLE=(X = 3, Y = 4, STARTTIME = 6, LIFETIME = 4)
MOLE=(X = 9, Y = 5, STARTTIME = 10, LIFETIME = 4)
MOLE=(X = 8, Y = 4, STARTTIME = 14, LIFETIME = 4)
MOLE=(X = 1, Y = 2, STARTTIME = 18, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 22, LIFETIME = 4)
MOLE=(X = 1, Y = 6, STARTTIME = 26, LIFETIME = 4)
MOLE=(X = 4, Y = 5, STARTTIME = 30, LIFETIME = 4)
MOLE=(X = 8, Y = 2, STARTTIME = 34, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 38, LIFETIME = 4)
MOLE=(X = 2, Y = 6, STARTTIME = 42, LIFETIME = 4)
MOLE=(X = 8, Y = 5, STARTTIME = 46, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 50, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 54, LIFETIME = 4)
MOLE=(X = 4, Y = 2, STARTTIME = 58, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 62, LIFETIME = 4)
MOLE=(X = 2, Y = 5, STARTTIME = 66, LIFETIME = 4)
MOLE=(X = 7, Y = 6, STARTTIME = 70, LIFETIME = 4)
MOLE=(X = 9, Y = 6, STARTTIME = 74, LIFETIME = 4)
```

**Comment by QuentinDaveau** [comment]
@bastianilso I've implemented the file loader and the pattern parser (to parse the loaded pattern file into a readable format for the PatternPlayer, which will play the pattern at runtime). I made a small modification to the pattern format though, I've replaced the first `=` by a `:`. It's easier for me in the code. In this way the test example looks like this:

```
WALL:(ROW = 1, COL = 10)
MOLE:(X = 1, Y = 1, STARTDELAY = 2, LIFETIME = 4)
MOLE:(X = 10, Y = 1, STARTDELAY = 2, LIFETIME = 4)
MOLE:(X = 2, Y = 1, STARTDELAY = 6, LIFETIME = 4)
MOLE:(X = 9, Y = 1, STARTDELAY = 6, LIFETIME = 4)
MOLE:(X = 3, Y = 1, STARTDELAY = 10, LIFETIME = 4)
MOLE:(X = 8, Y = 1, STARTDELAY = 10, LIFETIME = 4)
MOLE:(X = 4, Y = 1, STARTDELAY = 14, LIFETIME = 4)
MOLE:(X = 7, Y = 1, STARTDELAY = 14, LIFETIME = 4)
MOLE:(X = 5, Y = 1, STARTDELAY = 18, LIFETIME = 4)
MOLE:(X = 6, Y = 1, STARTDELAY = 18, LIFETIME = 4)
MOLE:(X = 4, Y = 1, STARTDELAY = 22, LIFETIME = 4)
MOLE:(X = 7, Y = 1, STARTDELAY = 22, LIFETIME = 4)
MOLE:(X = 3, Y = 1, STARTDELAY = 26, LIFETIME = 4)
MOLE:(X = 8, Y = 1, STARTDELAY = 26, LIFETIME = 4)
MOLE:(X = 2, Y = 1, STARTDELAY = 30, LIFETIME = 4)
MOLE:(X = 9, Y = 1, STARTDELAY = 30, LIFETIME = 4)
MOLE:(X = 1, Y = 1, STARTDELAY = 34, LIFETIME = 4)
MOLE:(X = 10, Y = 1, STARTDELAY = 34, LIFETIME = 4)
MOLE:(X = 10, Y = 1, STARTDELAY = 40, LIFETIME = 4)
MOLE:(X = 9, Y = 1, STARTDELAY = 44, LIFETIME = 4)
MOLE:(X = 8, Y = 1, STARTDELAY = 48, LIFETIME = 4)
MOLE:(X = 7, Y = 1, STARTDELAY = 52, LIFETIME = 4)
MOLE:(X = 6, Y = 1, STARTDELAY = 56, LIFETIME = 4)
MOLE:(X = 5, Y = 1, STARTDELAY = 60, LIFETIME = 4)
MOLE:(X = 4, Y = 1, STARTDELAY = 64, LIFETIME = 4)
MOLE:(X = 3, Y = 1, STARTDELAY = 64, LIFETIME = 4)
MOLE:(X = 2, Y = 1, STARTDELAY = 64, LIFETIME = 4)
MOLE:(X = 1, Y = 1, STARTDELAY = 64, LIFETIME = 4)
MOLE:(X = 2, Y = 1, STARTDELAY = 68, LIFETIME = 4)
MOLE:(X = 3, Y = 1, STARTDELAY = 72, LIFETIME = 4)
MOLE:(X = 4, Y = 1, STARTDELAY = 76, LIFETIME = 4)
MOLE:(X = 5, Y = 1, STARTDELAY = 80, LIFETIME = 4)
MOLE:(X = 6, Y = 1, STARTDELAY = 84, LIFETIME = 4)
MOLE:(X = 7, Y = 1, STARTDELAY = 88, LIFETIME = 4)
MOLE:(X = 8, Y = 1, STARTDELAY = 92, LIFETIME = 4)
MOLE:(X = 9, Y = 1, STARTDELAY = 96, LIFETIME = 4)
MOLE:(X = 10, Y = 1, STARTDELAY = 100, LIFETIME = 4)
```

**Comment by QuentinDaveau** [comment]
The working pattern player/loader/parser. Is affected by game pause/stop and sets the game time to the pattern duration. Can change any modifier (distractor), any property of the wall, game difficulty and can randomize elements. It still needs some tweaking though:

![patterns](https://user-images.githubusercontent.com/45624296/71915147-714f9200-317b-11ea-8e6a-286e275de2b5.gif)

The pattern used for the demo:

```
WALL:(ROW = 6, COL = 10, SIZEX = 5, SIZEY = 3.2, CURVEX = 0.6, CURVEY = 0.4, MAXANGLE = 80, MOLESCALEX = 30, MOLESCALEY = 30)
WAIT:(TIME=0.5)
MOLE:(X = 1, Y = 3, LIFETIME = 0.25)
MOLE:(X = 10, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 2, Y = 3, LIFETIME = 0.25)
MOLE:(X = 9, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 3, Y = 3, LIFETIME = 0.25)
MOLE:(X = 8, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 4, Y = 3, LIFETIME = 0.25)
MOLE:(X = 7, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 5, Y = 3, LIFETIME = 1)
MOLE:(X = 6, Y = 3, LIFETIME = 1)
WAIT:(TIME=1)
DISTRACTOR:(MIRROR = true, DUALTASK = false)
WAIT:(TIME=1)
MOLE:(X = 5, Y = 3, LIFETIME = 1)
MOLE:(X = 6, Y = 3, LIFETIME = 1)
WAIT:(TIME=1)
MOLE:(X = 4, Y = 3, LIFETIME = 0.25)
MOLE:(X = 7, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 3, Y = 3, LIFETIME = 0.25)
MOLE:(X = 8, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 2, Y = 3, LIFETIME = 0.25)
MOLE:(X = 9, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 1, Y = 3, LIFETIME = 0.25)
MOLE:(X = 10, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.5)
WALL:(ROW = 5, COL = 5, SIZEX = 1, SIZEY = 1, CURVEX = 0.1, CURVEY = 0.1, MAXANGLE = 10, MOLESCALEX = 10, MOLESCALEY = 10)
MOLE:(X = 2, Y = 2, STARTDELAY = 0.25, LIFETIME = 1)
MOLE:(X = 4, Y = 2, STARTDELAY = 0.5, LIFETIME = 0.75)
MOLE:(X = 4, Y = 4, STARTDELAY = 0.75, LIFETIME = 0.5)
MOLE:(X = 2, Y = 4, STARTDELAY = 1, LIFETIME = 0.25)
WAIT:(TIME=2.5)
```

**Comment by bastianilso** [comment]
@QuentinDaveau nice demo, could you please explain what each of the variables do?
What is the difference between using `STARTDELAY` and `WAIT` ?
What does `DISTRACTOR` mean? What does `MIRROR` and `DUALTASK` mean?
Why can `SIZEX` and `SIZEY` be set to float values? What are they?
What is `MOLESCALEX` and `MOLESCALEY`?

**Comment by QuentinDaveau** [comment]
@bastianilso `STARTDELAY` and `WAIT` do in overall the same thing. Both are implemented to simplify the creation of patterns. The main issue with `STARTDELAY` is that it doesn't affect the following commands, which can result in a really messy pattern file for a long pattern. `WAIT`, on the other hand, affects the following commands, allowing to create a "timeline". I put both in the demo to show that both option are possible.

`DISTRACTOR` are simply the different modifiers (mirror effect, eye patch...).

`SIZEX` and `SIZEY` are the size of the wall, not to be mistaken with `ROW` and `COL` which are the number of Mole columns and rows.

`MOLESCALEX` and `MOLESCALEY` are the scale of the Moles, which is controlled by the wall. That's why it is possible to regenerate a small wall with small Moles in the demo.

**Comment by bastianilso** [comment]
@QuentinDaveau OK Sounds good.

I think by `DISTRACTOR` we want to talk about the "Red Moles that you are not supposed to press" - in clinical litterature / research, these are called _distractors_.
For the purpose of applying modifiers like mirror effect or eye patch, I think we could instead use  the keyword `MODIFIER`.

I think, to make it easier to write the pattern files, we should keep configuration parts optional e.g. have default values for `SIZEX`, `SIZEY`, `COL`, `ROW`, `MOLESCALEX`, `MOLESCALEY` etc.

**Comment by QuentinDaveau** [comment]
@bastianilso oooh, my bad. I don't know why, I thought that by `DISTRACTOR` you meant the modifiers. For the fake moles, it is an option in the Mole spawn line. I forgot to showcase it in the demo (it is basically the `FAKE = true` option). Should I leave as an option in `MOLE` or should I implement it as its own `DISTRACTOR` command ?

For the `SIZEX` and all, they are all optionnal, which mean that you can call the `WALL` command with whatever argument you want. Also the `WALL` option isn't necessary in the pattern, it is to update the current wall, so if you never call it it will use the default wall. In the demo I've put it at the beginning of the pattern to reset the wall since I modify it another time in the pattern.

**Comment by bastianilso** [comment]
I think calling it `DISTRACTOR` would be good, makes it clear to see where they are in the pattern file - and we might want to reduce/add more options to `MOLE` which wouldnt make sense for moles you are not supposed to press in the future.

and sounds good with keeping all the other things optional.
From where are the pattern files currently loaded? I think it would be nice to have them (and also profiles) in [Application.persistentDataPath](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html) - so when we make WAM binary releases, we can still access those folders. 

In the future we might want to do something more sophisticated for the `WALL`. Usually when adding or removing moles to a wall, I would rather not start a trial-and-error for getting the right size of the wall too - I would assume the wall expands as more rows/cols of moles are added. However, that might not be true in the opposite direction (we may want to keep the wall the same default size, even with only a single row of moles available).

**Comment by QuentinDaveau** [comment]
> I think calling it `DISTRACTOR` would be good, makes it clear to see where they are in the pattern file - and we might want to reduce/add more options to `MOLE` which wouldnt make sense for moles you are not supposed to press in the future.

Makes sens. I'll implement the `DISTRACTOR` then.

> From where are the pattern files currently loaded? I think it would be nice to have them (and also profiles) in Application.persistentDataPath - so when we make WAM binary releases, we can still access those folders.

The pattern files and profiles are already loaded from persistentDataPath (Appdata/LocalLow/...).

> In the future we might want to do something more sophisticated for the WALL.

I agree. The generation of the wall will need more work in the future. For now the wall and the moles are closely linked together, that's why it is currently impossible to generate a single row of moles for example (it causes errors in the wall generation). The best would be to consider the wall and the moles as two distinct entities in the future (currently they are both part of the WallManager).

**Comment by QuentinDaveau** [comment]
I've now added comments to the patterns (any text following `//` is considered a comment and ignored).
As a temporary implementation to load/change patterns when the game is running (since we can't do that in the UI), I've added an input field in the editor. If the field is empty, the game uses no pattern. If the field matches the name of an existing pattern, the game will use it. It's a bit sketchy, but at least it allows us to enable/disable/change pattern at runtime.

I'll make a new issue to create an UI for the pattern selection.

**Comment by QuentinDaveau** [comment]
Issue fixed with merging of #56. Closing the issue.

**Comment by bastianilso** [comment]
@QuentinDaveau any chance I could get you to convert/adapt the two patterns I posted into the new format? We will be testing participants on those on Monday. I dont know whether the STARTTIME/LIFETIME values I set makes any sense, (ie. is it playable), but we can perform some tests and update accordingly.

```
WALL=(ROW = 6, COL = 9)
MOLE=(X = 7, Y = 3, STARTTIME = 2, LIFETIME = 4)
MOLE=(X = 3, Y = 4, STARTTIME = 6, LIFETIME = 4)
MOLE=(X = 9, Y = 5, STARTTIME = 10, LIFETIME = 4)
MOLE=(X = 8, Y = 4, STARTTIME = 14, LIFETIME = 4)
MOLE=(X = 1, Y = 2, STARTTIME = 18, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 22, LIFETIME = 4)
MOLE=(X = 1, Y = 6, STARTTIME = 26, LIFETIME = 4)
MOLE=(X = 4, Y = 5, STARTTIME = 30, LIFETIME = 4)
MOLE=(X = 8, Y = 2, STARTTIME = 34, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 38, LIFETIME = 4)
MOLE=(X = 2, Y = 6, STARTTIME = 42, LIFETIME = 4)
MOLE=(X = 8, Y = 5, STARTTIME = 46, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 50, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 54, LIFETIME = 4)
MOLE=(X = 4, Y = 2, STARTTIME = 58, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 62, LIFETIME = 4)
MOLE=(X = 2, Y = 5, STARTTIME = 66, LIFETIME = 4)
MOLE=(X = 7, Y = 6, STARTTIME = 70, LIFETIME = 4)
MOLE=(X = 9, Y = 6, STARTTIME = 74, LIFETIME = 4)
```

```
WALL=(ROW = 1, COL = 10)
MOLE=(X = 1, Y = 1, STARTTIME = 2, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 2, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 6, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 6, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 10, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 10, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 14, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 14, LIFETIME = 4)
MOLE=(X = 5, Y = 1, STARTTIME = 18, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 18, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 22, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 22, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 26, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 26, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 30, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 30, LIFETIME = 4)
MOLE=(X = 1, Y = 1, STARTTIME = 34, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 34, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 40, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 44, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 48, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 52, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 56, LIFETIME = 4)
MOLE=(X = 5, Y = 1, STARTTIME = 60, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 1, Y = 1, STARTTIME = 64, LIFETIME = 4)
MOLE=(X = 2, Y = 1, STARTTIME = 68, LIFETIME = 4)
MOLE=(X = 3, Y = 1, STARTTIME = 72, LIFETIME = 4)
MOLE=(X = 4, Y = 1, STARTTIME = 76, LIFETIME = 4)
MOLE=(X = 5, Y = 1, STARTTIME = 80, LIFETIME = 4)
MOLE=(X = 6, Y = 1, STARTTIME = 84, LIFETIME = 4)
MOLE=(X = 7, Y = 1, STARTTIME = 88, LIFETIME = 4)
MOLE=(X = 8, Y = 1, STARTTIME = 92, LIFETIME = 4)
MOLE=(X = 9, Y = 1, STARTTIME = 96, LIFETIME = 4)
MOLE=(X = 10, Y = 1, STARTTIME = 100, LIFETIME = 4)
```

**Comment by QuentinDaveau** [comment]
@bastianilso Sure, I'll convert them for monday.
