### ISSUE TITLE
Main Menu: Edit Participant Number, Test Number, Test Duration

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#6]
First see issue #4 and issue issue #2.

It would be nice, if one could edit the test metadata directly from the main menu, like shown below.

![whack-a-mole-editable-test-metadata](https://user-images.githubusercontent.com/3967945/61283419-62d08100-a7bd-11e9-848b-2ff3702ca44e.png)

**Comment by QuentinDaveau** [comment]
Implemented through issue #17

**Comment by QuentinDaveau** [comment]
Issue fixed with pull request #22. Closing the issue.
