### ISSUE TITLE
Logger: Log VR information

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#7]
First, see issue #2, before this one.

It would be nice with some extended logging info, which logs the VR controller and the VR headset. My suggestions below:

- [x] Log ControllerPosWorld which is the world position of the player's VR controller.
- [x] Log ControllerRotEuler which is the rotation of the player's VR controller at (transform.eulerAngles NOT transform.rotation)
- [x] Log ControllerRotTravel which is how much the controller has travelled since the last event. This requires you to sample the controller's rotation every frame and calculate a total distance from it.
- [x] Log LaserRay_TravelDistancePosWorld which is an aggregate of how far the Laser shooting from the controller has travelled since the last event. This requires you to sample the laser's position every frame and calculate the total distance travelled from it.

- [x] Log Head_PosWorld which is the position of the headset in world coordinates (transform.position).
- [x] Log Head_RotEuler which is the rotation of the headset in Euler angles (transform.eulerAngles NOT transform.rotation).
- [x] Log Head_RotTravel which is how much the head has rotated since the last event. This requires you to sample the head's rotation every frame and calculate the total distance from it.

**Comment by QuentinDaveau** [comment]
Issue fixed in merging of branch #23. Closing the issue.
