### ISSUE TITLE
Mirror Modifier: Use symmetry axis 

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#72]
I cannot find an issue for this, so this must have been verbal discussion. But during the discussion with Lars in November, it was proposed to change the mirror modifier such that it relates more to[ the real-world mirror application](https://www.youtube.com/watch?v=1BnsQO7a4Og&t=111s).

![image](https://user-images.githubusercontent.com/3967945/73917673-2f238880-48c0-11ea-90e3-185ad3b76d18.png)

Concretely it means:
- We design a mirror with a fixed axis, where the mirroring is happening. and which the patient cannot look beyond.
- The patient can only shoot moles in one side of the wall (the wall is in fact half the size and everything happening on one side of the wall is mirrored to the other side as well).

**Comment by larsevald** [comment]
The 'old' mirroring of the x axis could still be used for assessment purposes

**Comment by bastianilso** [comment]
Oct 7th notes:
- Moles should also be mirrored. (x symmetric targets)
- The healthy-side controller should be shown on both sides.
- The "unhealthy-side" controller should be turned on, but invisible in VR (so we just collect data from it).

**Comment by bastianilso** [comment]
Here is a first "test implementation", using the [Mirror example](https://en.wikibooks.org/wiki/Cg_Programming/Unity/Mirrors) from Martin Kraus' CG Programming book.
![physical-mirror-test gif](https://user-images.githubusercontent.com/3967945/95725853-785e8000-0c78-11eb-96fb-4619d8f273eb.gif)

Pros/Cons:
- Pro: It's a "physical mirror" - everything the user can see in VR is mirrored, it has little dependency on how other parts work in Whack-a-mole, so it is easy to maintain.
- Pro: We can choose which objects to hide from the mirror easily (but which is still visible on the other side).
- Con: The mirror passes through a render texture which limits our resolution, especially when the viewer sits at a close angle to it. Currently I render onto 2 4k textures, and you can see how the further ends of the whack-a-mole wall seems pixelized. Shadows don't render either, but this might be fixable, I will talk to martin.

This is just a test implementation: It does not currently work with the UI - and the wall is still full size, meaning half of the moles spawn on a side you cannot see.

An alternative implementation which is much more "programmatically expensive" to make and maintain, is to create physical copies of all objects and update their positions at all times.

**Comment by bastianilso** [comment]
Spoke with martin kraus, and arrived at the following alternative implementation:
- Mirror the controller and motorspace by creating a clone of it and let it operate in the reverse direction. This could be what this alternative mirror mode could do.
- Don't mirror the wall - instead, either implement a mode in which the wall's moles appear symmetrical, or create a specific treatment program with a pre-programmed pattern which does this.

For the time being I will upload what I currently have, and then move onto other tasks.

**Comment by larsevald** [comment]
I reckon that Martins suggestion would do the trick

**Comment by bastianilso** [comment]
I took some time today to investigate the effects of implementing geometric mirror (aka martins suggestion).

Things that are easy to do:
- Mirror the controller itself.
- Mirror the motorspace.

Things that are harder/uglier to do:
- Mirror the laser.
- Mirror shooting.

The main issue is that our "fake controller" has no conception of shooting and of "hovering" on the wall.
So it requires copy-pasting parts of the real code - and then we get into trouble later keeping it all in sync, should the behavior change (when to show laser, how to react when trigger is pressed etc). I'll keep thinking about this..

![geometric-mirror gif](https://user-images.githubusercontent.com/3967945/98533625-81e10500-2283-11eb-9662-0c1bec15a261.gif)

**Comment by bastianilso** [comment]
So we have a working implementation of geometric mirror now.

The good news:
- The geometric mirror can be turned on and off independently. Very few changes required to the existing code.
- The function mirrors across a symmetry line at "0" in the X axis (the center of the wall, I have visualized it as a blue line). If you wish to have the mirrored controller on your left side, you should calibrate your real motorspace to be on the right side of the axis and vice versa.
- The geometric mirror only affects controllers and motor space and can be used regardless of what the wall is doing. Two "Mole Hit/Missed" events are registered, for every shot in this mode.

Limitations:
- The player has to stand centered to the wall. Moving further away from the center, moves the mirrored geometry further away. In the future, we could make the symmetry line adjustable in the future. Regardless though, we ideally want the player centered to the wall anyway.
- To make the mirror work with as little interference to existing code as possible, there is some code duplication, mainly concerning the shooting animation. This can be fixed later with some refactoring.

![geometric-mirror3 gif](https://user-images.githubusercontent.com/3967945/98651335-67b62e00-233a-11eb-9a83-6c67065090e4.gif)

**Comment by bastianilso** [comment]
Todo:
 * Update the mirrored motorspace to use same settings as the primary motorspace, when it is enabled.

**Comment by bastianilso** [comment]
Fixed with #128
