### ISSUE TITLE
Eye Patch modifier: Use blocking object.

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#73]
Currently our eye patch modifier turns off the individual lenses in the HMD directly, much like wearing a physical eye patch. However, for the clinical outcomes we might want rather to let the eye patch be a blocking object in the 3D space. This might be useful as an additional modifier next to the others.

The blocking object should be tied to the HMD rotation/position and reach infinitely into the gamespace (or as much as makes sense). It should block the view, much like if you lean yourself next to a wall.

![image](https://user-images.githubusercontent.com/3967945/73918172-57f84d80-48c1-11ea-8b78-d8aec463eb59.png)

The main difference between an eye-patch and this behavior is that it force patients to rotate their head more.

**Comment by larsevald** [comment]
The half-field eye-patching should be fixed to the HMD and turn with the head, almost like a cardboard glued to your cheek and ear of the unimpaired hemispace

**Comment by bastianilso** [comment]
Oct 07th notes:
- we mimick that the patients have a wall moving along with their head
- it should be possible to vary how close you are to the wall.

**Comment by bastianilso** [comment]
Here is an initial simple implementation.
The implementation removes the view of the Whack-A-Mole wall in either left or right side of the visual field.
Right now the transition is very sudden. I want to investigate whether we can make the transition more gradual, as if the wall fades out.

![eyepatch-sky gif](https://user-images.githubusercontent.com/3967945/95841568-cc836600-0d45-11eb-8089-d28d748738a7.gif)

**Comment by bastianilso** [comment]
First iteration implemented in #104.

To do:
- Instead of a hard cut-off between masked area and wall, it would be nice if we could make a soft transition.
![image](https://user-images.githubusercontent.com/3967945/95953904-d61ad580-0dfa-11eb-95fa-b5e7cbce5f12.png)
- The modifier should allow controlling how much is being masked.

**Comment by larsevald** [comment]
I believe this is much better. I'm excited to learn how patients will react to this.

**Comment by bastianilso** [comment]
After some digging into GPU programming, I figured out a way to create a soft transition.
I will add some UI to control how much of the wall becomes covered.

![eyepatch-gradient2 gif](https://user-images.githubusercontent.com/3967945/98680482-c4790f00-2361-11eb-93b1-92cf3e85a37a.gif)

**Comment by IrisBrunner** [comment]
Looks much better now, great!


Iris Brunner, PhD, associate professor
University of Aarhus, Denmark
Hammel Neurocenter
Phone: +4578419078
Mobile: +4560568195
http://pure.au.dk/portal/en/iribru@rm.dk



________________________________
Fra: Bastian Ilso <notifications@github.com>
Sendt: 10. november 2020 14:35
Til: med-material/Whack_A_Mole_VR
Cc: Subscribed
Emne: Re: [med-material/Whack_A_Mole_VR] Eye Patch modifier: Use blocking object. (#73)


After some digging into GPU programming, I figured out a way to create a soft transition.
I will add some UI to control how much of the wall becomes covered.

[eyepatch-gradient2 gif]<https://user-images.githubusercontent.com/3967945/98680482-c4790f00-2361-11eb-93b1-92cf3e85a37a.gif>

[https://user-images.githubusercontent.com/3967945/98680482-c4790f00-2361-11eb-93b1-92cf3e85a37a.gif]

**Comment by hendrikknoche** [comment]
Would love to understand the GPU part when we have a minute 😊

best

Hendrik

--
Hendrik Knoche
Associate professor (PhD)
Department of Architecture and Media Technology

Aalborg University | Rendsburggade 14 | 9000 Aalborg | Room 5-360
tinyurl.com/aau-hendrik-knoche

m: +45 9940 2661
m: +45 6051 3546
