### ISSUE TITLE
Pointer: Ignore Controller Rotation

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#74]
Currently the VR  pointer uses both rotation and position in the VR space to determine where the laser is shooting. This leads to users not utilizing the movement of their arm very much. Especially for stroke patients, it means they move their arm into the affected space very much.

One way to solve this is by ignoring the controllers rotation. However, this might lead to akward relationship (you rotate the controller in the real world, but the VR controller does not seem to react). So instead of removing controller rotation, we can instead parent a "bubble" from which the laser is emitted - the bubble is a sphere that is only parented to the controller by position, and not by rotation.

![image](https://user-images.githubusercontent.com/3967945/73918581-2cc22e00-48c2-11ea-866a-bbaec0e661be.png)

**Comment by larsevald** [comment]
Maybe this could work - as it is implemented now, it is very easy to rely on wrist movement. Alternatively you should interact directly with the moles, as we have discussed previously, but this causes other challenges

**Comment by hendrikknoche** [comment]
I think we should consider using only x/y position of the controller that is scaled by the manageable motor space of the patient.

**Comment by bastianilso** [comment]
Progress Update: We now have a visualized motor space with upper and lower boundaries (currently only settable from Unity, but therapist UI will come soon).

Next Step: Implement the Wall Space and make the spatial conversion for the laser.

![laser-motor-space gif](https://user-images.githubusercontent.com/3967945/94919008-f15d1b00-04b3-11eb-8d00-7fa6928ee4c9.gif)

**Comment by bastianilso** [comment]
Update: Motor space to wall space conversion is now working, and the game is playable again.
I will spend some remaining time polishing this up:
- Add better more visible cursor.
- Inhibit activation of the laser bubble when controller surpasses the motor space.
- Indicate states on the laser bubble (active or out of bounds). Alternatively, we can turn the bubble invisible. 
- Make it possible to control the motor space width/height/position from therapist UI.
![laser-motor-to-wall2 gif](https://user-images.githubusercontent.com/3967945/95185605-31c8db80-07c9-11eb-9160-85319f8e3400.gif)

**Comment by bastianilso** [comment]
Implemented in #88
