### ISSUE TITLE
Game: Add Countdown

### ISSUE THREAD

**Issue by bastianilso** [med-material/Whack_A_Mole_VR#84]
Currently when the therapist press start, the game starts right away. It would be good to have a countdown before the game starts.

**Comment by bastianilso** [comment]
aiming for something simple here as the initial starting point:
![image](https://user-images.githubusercontent.com/3967945/94791150-86d6ad00-03d7-11eb-9927-a2ccbd38be7e.png)

currently the wall doesnt show up until the game starts, might be something to open up another issue for.

**Comment by hendrikknoche** [comment]
looks good. how should we treat the language problem?

**Comment by bastianilso** [comment]
Either we re-write it all to Danish, or we spend some dev time implementing XML multi-language support (see [example in here](https://forum.unity.com/threads/add-multiple-language-support-to-your-unity-projects.206271/))..this is a custom solution, unfortunately the Unity framework doesn't provide much help in this area (AFAIK).

**Comment by hendrikknoche** [comment]
Maybe in the meantime we can simply refactor to Danish and 
somehow make the thing searchable with tags so we could easily produce an English version
